Repository urinaner/sejong-dibb, pull requests merged in 2024-10, with the labels that each got.

#40 [BE] JWT 버그 수정
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/org/example/backend/admin/controller/AdminController.java
  backend/src/main/java/org/example/backend/admin/controller/MainController.java
  backend/src/main/java/org/example/backend/admin/domain/dto/AdminResDto.java
  backend/src/main/java/org/example/backend/admin/domain/dto/SignInReqDto.java
  backend/src/main/java/org/example/backend/admin/domain/dto/SignInResDto.java
  backend/src/main/java/org/example/backend/admin/domain/entity/Admin.java
  backend/src/main/java/org/example/backend/admin/domain/entity/CustomUserDetails.java
  backend/src/main/java/org/example/backend/admin/domain/mapper/SignInMapper.java
  backend/src/main/java/org/example/backend/admin/repository/AdminRepository.java
  backend/src/main/java/org/example/backend/admin/service/AdminService.java
  backend/src/main/java/org/example/backend/admin/service/CustomUserDetailService.java
  backend/src/main/java/org/example/backend/admin/service/CustomUserDetailsService.java
  backend/src/main/java/org/example/backend/admin/service/TokenBlackListService.java
  backend/src/main/java/org/example/backend/global/config/JwtAuthenticationFilter.java
  backend/src/main/java/org/example/backend/global/config/JwtTokenProvider.java
  backend/src/main/java/org/example/backend/global/config/SecurityConfig.java
  backend/src/main/java/org/example/backend/jwt/JWTFilter.java
  backend/src/main/java/org/example/backend/jwt/JWTUtil.java
  backend/src/main/java/org/example/backend/jwt/LoginFilter.java
  backend/src/main/resources/application.properties
  backend/src/test/java/org/example/backend/PasswordEncoderExample.java
Labels: bug, 😄 BE

#45 [FE] Modal UI 개선 및 Context 적용
  frontend/src/App.tsx
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/Modal/useModal.tsx
  frontend/src/context/ModalContext.tsx
  frontend/src/pages/Auth/SignIn.tsx
  frontend/src/styles/ModalStyle.ts
Labels: enhancement, 🙂 FE, refactor

#49 #47 [FE] Dockerfile 구성
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/package.json
Labels: setting, 🙂 FE

#57 [BE] 도커 파일 생성
  backend/Dockerfile
Labels: setting, 😄 BE

#50 [FE] 대학(학사/입학 하이퍼링크) 페이지 구현
  frontend/public/academic-guide.svg
  frontend/public/admission-guide.svg
  frontend/public/bachelor-guide.svg
  frontend/public/index.html
  frontend/public/scholarship-guide.svg
  frontend/src/App.tsx
  frontend/src/components/Footer/Footer.tsx
  frontend/src/pages/Undergraduate/Hyperlink.tsx
  frontend/src/pages/Undergraduate/styles/UndergraduateStyle.tsx
  frontend/src/styles/FooterStyle.ts
Labels: enhancement, 🙂 FE

#66 [FE] 학과 소개 페이지 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/images/main_picture.svg
  frontend/src/index.css
  frontend/src/pages/About/About.tsx
  frontend/src/pages/About/AboutStyle.ts
Labels: enhancement, 🙂 FE

#64 [BE] 도커 db 연결
  backend/.gitignore
  backend/src/main/java/org/example/backend/admin/domain/entity/Admin.java
Labels: enhancement, 😄 BE

#68 [BE] 더미 데이터 넣은 backup 파일
  backend/backup.sql
Labels: enhancement, 😄 BE

#72 [BE] swagger 로그인 api 추가
  backend/src/main/java/org/example/backend/admin/domain/dto/AdminResDto.java
  backend/src/main/java/org/example/backend/admin/domain/dto/SignInReqDto.java
  backend/src/main/java/org/example/backend/admin/domain/dto/SignInResDto.java
  backend/src/main/java/org/example/backend/admin/repository/AdminRepository.java
  backend/src/main/java/org/example/backend/admin/service/AdminService.java
  backend/src/main/java/org/example/backend/admin/service/CustomUserDetailsService.java
  backend/src/main/java/org/example/backend/global/config/CustomAuthenticationFailureHandler.java
  backend/src/main/java/org/example/backend/global/config/SecurityConfig.java
  backend/src/main/java/org/example/backend/global/config/SwaggerConfig.java
  backend/src/main/java/org/example/backend/jwt/JWTFilter.java
  backend/src/main/java/org/example/backend/jwt/JWTUtil.java
  backend/src/main/java/org/example/backend/jwt/LoginFilter.java
Labels: enhancement, 😄 BE

#61 #60 refactor: uri 주소 변경 및 로그인 json 값 수정
  frontend/.env
  frontend/src/context/AuthContext.tsx
  frontend/src/pages/Auth/SignIn.tsx
Labels: enhancement, setting, 😄 BE, 🙂 FE, refactor

#76 [FE] 교수 소개 페이지 구현
  frontend/public/horizontalBar.svg
  frontend/src/App.tsx
  frontend/src/components/Footer/Footer.tsx
  frontend/src/pages/About/Faculty.tsx
  frontend/src/pages/About/FacultyStyle.ts
  frontend/src/pages/Undergraduate/styles/UndergraduateStyle.tsx
Labels: enhancement, 🙂 FE

#82 #81 fix: 부서테스트빌드에러 수정
  backend/src/test/java/org/example/backend/department/controller/DepartmentControllerTest.java
  backend/src/test/java/org/example/backend/department/service/DepartmentServiceTest.java
Labels: 😄 BE

#79 [BE] docker 연결 수정 사항
  backend/.env.example
  backend/.gitignore
  backend/Dockerfile
  backend/docker-compose-stable.yml
  backend/src/main/java/org/example/backend/global/config/SwaggerConfig.java
  backend/src/test/java/org/example/backend/department/repository/DepartmentRepositoryTest.java
  backend/src/test/java/org/example/backend/department/service/DepartmentServiceTest.java
  backend/src/test/java/org/example/backend/professor/service/ProfessorServiceTest.java
Labels: setting, 😄 BE

#80 [BE] feat : 나머지 엔티티 설계
  backend/src/main/java/org/example/backend/board/domain/entity/Board.java
  backend/src/main/java/org/example/backend/seminar/domain/entity/Seminar.java
  backend/src/main/java/org/example/backend/thesis/domain/entity/Thesis.java
Labels: 😄 BE
