Repository urinaner/sejong-dibb, pull requests merged in 2024-09, with the labels that each got.

#3 #1 기능 추가: 프론트엔드 초기 세팅 및 의존성 추가
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.svg
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/styles/style.ts
  frontend/tsconfig.json
Labels: setting, 🙂 FE

#4 [BE] 백엔드 초기 세팅
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/org/example/backend/BackendApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/org/example/backend/BackendApplicationTests.java
Labels: setting, 😄 BE

#7 fix: 오류 수정
  frontend/.eslintrc.json
  frontend/.prettierrc
Labels: bug, 🙂 FE

#11 [BE] Feature/10: Professor 엔티티 및 기본적 CRUD 설계
  backend/build.gradle
  backend/src/main/java/org/example/backend/controller/ProfessorController.java
  backend/src/main/java/org/example/backend/domain/dto/ResponseDto.java
  backend/src/main/java/org/example/backend/domain/dto/professor/ProfessorReqDto.java
  backend/src/main/java/org/example/backend/domain/dto/professor/ProfessorResDto.java
  backend/src/main/java/org/example/backend/domain/entity/Professor.java
  backend/src/main/java/org/example/backend/domain/mapper/ProfessorMapper.java
  backend/src/main/java/org/example/backend/repository/ProfessorRepository.java
  backend/src/main/java/org/example/backend/service/ProfessorService.java
Labels: enhancement, 😄 BE

#13 [BE] Department 엔티티 및 CRUD
  .idea/vcs.xml
  .idea/workspace.xml
  backend/src/main/java/org/example/backend/controller/DepartmentController.java
  backend/src/main/java/org/example/backend/domain/dto/Department/DepartmentDto.java
  backend/src/main/java/org/example/backend/domain/entity/Department.java
  backend/src/main/java/org/example/backend/repository/DepartmentRepository.java
  backend/src/main/java/org/example/backend/service/DepartmentService.java
Labels: enhancement, 😄 BE

#16 [BE] refactor: 디렉토리 구조 변경
  backend/src/main/java/org/example/backend/department/controller/DepartmentController.java
  backend/src/main/java/org/example/backend/department/domain/dto/Department/DepartmentDto.java
  backend/src/main/java/org/example/backend/department/domain/entity/Department.java
  backend/src/main/java/org/example/backend/department/domain/mapper/DepartmentMapper.java
  backend/src/main/java/org/example/backend/department/repository/DepartmentRepository.java
  backend/src/main/java/org/example/backend/department/service/DepartmentService.java
  backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
  backend/src/main/java/org/example/backend/professor/domain/dto/ResponseDto.java
  backend/src/main/java/org/example/backend/professor/domain/dto/professor/ProfessorReqDto.java
  backend/src/main/java/org/example/backend/professor/domain/dto/professor/ProfessorResDto.java
  backend/src/main/java/org/example/backend/professor/domain/entity/Professor.java
  backend/src/main/java/org/example/backend/professor/domain/mapper/ProfessorMapper.java
  backend/src/main/java/org/example/backend/professor/repository/ProfessorRepository.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
Labels: enhancement, 😄 BE

#21 [BE] refactor: Mapper 적용
  backend/src/main/java/org/example/backend/department/controller/DepartmentController.java
  backend/src/main/java/org/example/backend/department/domain/dto/Department/DepartmentDto.java
  backend/src/main/java/org/example/backend/department/domain/dto/Department/DepartmentReqDto.java
  backend/src/main/java/org/example/backend/department/domain/dto/Department/DepartmentResDto.java
  backend/src/main/java/org/example/backend/department/domain/entity/Department.java
  backend/src/main/java/org/example/backend/department/domain/mapper/DepartmentMapper.java
  backend/src/main/java/org/example/backend/department/service/DepartmentService.java
Labels: enhancement, 😄 BE

#24 [FE] feature: 푸터 레이아웃 구현
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/adminLoginBtn.svg
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/Footer/Footer.tsx
  frontend/src/styles/FooterStyle.ts
  frontend/src/styles/style.ts
Labels: enhancement, 🙂 FE

#26 [BE] 로그인 / 로그아웃 기능 개발
  backend/build.gradle
  backend/src/main/java/org/example/backend/admin/controller/AdminController.java
  backend/src/main/java/org/example/backend/admin/domain/dto/AccessTokenReq.java
  backend/src/main/java/org/example/backend/admin/domain/dto/AdminResDto.java
  backend/src/main/java/org/example/backend/admin/domain/dto/SignInReqDto.java
  backend/src/main/java/org/example/backend/admin/domain/dto/SingInResDto.java
  backend/src/main/java/org/example/backend/admin/domain/dto/TokenDto.java
  backend/src/main/java/org/example/backend/admin/domain/entity/Admin.java
  backend/src/main/java/org/example/backend/admin/domain/mapper/SignInMapper.java
  backend/src/main/java/org/example/backend/admin/repository/AdminRepository.java
  backend/src/main/java/org/example/backend/admin/service/AdminService.java
  backend/src/main/java/org/example/backend/admin/service/TokenBlackListService.java
  backend/src/main/java/org/example/backend/config/JwtAuthenticationFilter.java
  backend/src/main/java/org/example/backend/config/JwtTokenProvider.java
  backend/src/main/java/org/example/backend/config/SecurityConfig.java
  backend/src/main/java/org/example/backend/department/domain/entity/Department.java
Labels: enhancement, 😄 BE

#30 [BE] 빌드 오류 처리
  backend/src/main/java/org/example/backend/admin/domain/entity/Admin.java
  backend/src/main/java/org/example/backend/admin/domain/entity/CustomUserDetails.java
  backend/src/main/java/org/example/backend/admin/domain/mapper/SignInMapper.java
  backend/src/main/java/org/example/backend/admin/service/AdminService.java
  backend/src/main/java/org/example/backend/admin/service/CustomUserDetailService.java
  backend/src/main/java/org/example/backend/department/domain/mapper/DepartmentMapper.java
  backend/src/main/java/org/example/backend/global/config/CentralMapperConfig.java
  backend/src/main/java/org/example/backend/global/config/JwtAuthenticationFilter.java
  backend/src/main/java/org/example/backend/global/config/JwtTokenProvider.java
  backend/src/main/java/org/example/backend/global/config/SecurityConfig.java
  backend/src/main/java/org/example/backend/professor/domain/mapper/ProfessorMapper.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
Labels: bug, 😄 BE

#27 [BE] exception 중앙화
  backend/src/main/java/org/example/backend/admin/domain/entity/Admin.java
  backend/src/main/java/org/example/backend/admin/exception/AdminException.java
  backend/src/main/java/org/example/backend/admin/exception/AdminExceptionType.java
  backend/src/main/java/org/example/backend/admin/service/AdminService.java
  backend/src/main/java/org/example/backend/common/exception/BaseException.java
  backend/src/main/java/org/example/backend/common/exception/BaseExceptionType.java
  backend/src/main/java/org/example/backend/common/exception/ExceptionControllerAdvice.java
  backend/src/main/java/org/example/backend/common/exception/ExceptionResponse.java
  backend/src/main/java/org/example/backend/config/JwtAuthenticationFilter.java
  backend/src/main/java/org/example/backend/config/JwtTokenProvider.java
  backend/src/main/java/org/example/backend/config/SecurityConfig.java
  backend/src/main/java/org/example/backend/department/exception/DepartmentException.java
  backend/src/main/java/org/example/backend/department/exception/DepartmentExceptionType.java
  backend/src/main/java/org/example/backend/department/service/DepartmentService.java
  backend/src/main/java/org/example/backend/professor/exception/ProfessorException.java
  backend/src/main/java/org/example/backend/professor/exception/ProfessorExceptionType.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
Labels: enhancement, 😄 BE

#37 [FE] 모달 구현
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/Modal/useModal.tsx
  frontend/src/pages/Auth/SignIn.tsx
  frontend/src/styles/ModalStyle.ts
Labels: enhancement, 🙂 FE

#39 #38 chore: root 디렉터리에 잘못된 npm init 데이터 삭제
  package-lock.json
  package.json
Labels: bug, 🙂 FE
