Repository urinaner/sejong-dibb, pull requests merged in 2024-12, with the labels that each got.

#176 [FE] [REFACTOR] Modal 합성 컴포넌트 사용 리펙토링
  frontend/src/App.tsx
  frontend/src/AppContent.tsx
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/Modal/components/ModalCloseButton.tsx
  frontend/src/components/Modal/components/ModalContent.tsx
  frontend/src/components/Modal/components/ModalDeleteButton.tsx
  frontend/src/components/Modal/components/ModalFooter.tsx
  frontend/src/components/Modal/components/ModalHeader.tsx
  frontend/src/components/Modal/components/ModalRoot.tsx
  frontend/src/components/Modal/context/ModalContext.tsx
  frontend/src/components/Modal/hooks/useModal.ts
  frontend/src/components/Modal/hooks/useNoticeModals.ts
  frontend/src/components/Modal/index.ts
  frontend/src/components/Modal/styles/ModalStyles.ts
  frontend/src/components/Modal/templates/AlertModal.tsx
  frontend/src/components/Modal/templates/NoticeModals.tsx
  frontend/src/components/Modal/types/modal.types.ts
  frontend/src/components/Modal/utils/modalUtils.ts
  frontend/src/context/ModalContext.tsx
  frontend/src/context/ModalStyle.ts
  frontend/src/pages/About/Faculty/ProfessorCreate.tsx
  frontend/src/pages/About/Faculty/ProfessorDetail.tsx
  frontend/src/pages/About/Faculty/ProfileSection.tsx
  frontend/src/pages/Auth/AdminSignIn.tsx
  frontend/src/pages/News/NoticeBoard/NoticeCreate.tsx
  frontend/src/pages/News/NoticeBoard/NoticeDetail.tsx
  frontend/src/pages/News/NoticeBoard/NoticeEdit.tsx
  frontend/src/pages/News/Thesis/ThesisCreate.tsx
  frontend/src/pages/News/Thesis/ThesisDetail.tsx
  frontend/src/pages/News/Thesis/ThesisEdit.tsx
  frontend/src/pages/News/Thesis/ThesisForm.tsx
Labels: enhancement, 🙂 FE, refactor

#182 [BE] [REFACTOR] 예약 구현 리펙토링
  backend/backup.sql
  backend/src/main/java/org/example/backend/common/utils/TimeParsingUtils.java
  backend/src/main/java/org/example/backend/reservation/controller/ReservationController.java
  backend/src/main/java/org/example/backend/reservation/domain/RepetitionType.java
  backend/src/main/java/org/example/backend/reservation/domain/Reservation.java
  backend/src/main/java/org/example/backend/reservation/domain/ReservationStatus.java
  backend/src/main/java/org/example/backend/reservation/domain/dto/ReservationReqDto.java
  backend/src/main/java/org/example/backend/reservation/domain/dto/ReservationResDto.java
  backend/src/main/java/org/example/backend/reservation/repository/ReservationRepository.java
  backend/src/main/java/org/example/backend/reservation/service/ReservationService.java
  backend/src/main/java/org/example/backend/reservation/service/validation/ReservationValidator.java
  backend/src/main/java/org/example/backend/reservation/service/validation/strategy/ReservationOverlapValidator.java
  backend/src/main/java/org/example/backend/reservation/service/validation/strategy/ReservationValidationStrategy.java
  backend/src/main/java/org/example/backend/reservation/service/validation/strategy/TimeRangeValidator.java
  backend/src/main/java/org/example/backend/reservation/service/validation/strategy/TimeTableOverlapValidator.java
  backend/src/main/java/org/example/backend/room/domain/Room.java
  backend/src/main/java/org/example/backend/room/domain/controller/RoomController.java
  backend/src/main/java/org/example/backend/room/domain/dto/RoomReqDto.java
  backend/src/main/java/org/example/backend/room/domain/dto/RoomResDto.java
  backend/src/main/java/org/example/backend/room/exception/RoomException.java
  backend/src/main/java/org/example/backend/room/exception/RoomExceptionType.java
  backend/src/main/java/org/example/backend/room/repository/RoomRepository.java
  backend/src/main/java/org/example/backend/room/service/RoomService.java
  backend/src/main/java/org/example/backend/seminarRoom/domain/controller/SeminarRoomController.java
  backend/src/main/java/org/example/backend/seminarRoom/domain/dto/SeminarRoomResDto.java
  backend/src/main/java/org/example/backend/seminarRoom/exception/SeminarRoomException.java
  backend/src/main/java/org/example/backend/seminarRoom/repository/SeminarRoomRepository.java
  backend/src/main/java/org/example/backend/seminarRoom/service/SeminarRoomService.java
  backend/src/main/java/org/example/backend/timetable/controller/TimetableController.java
  backend/src/main/java/org/example/backend/timetable/domain/Timetable.java
  backend/src/main/java/org/example/backend/timetable/domain/WeekDay.java
  backend/src/main/java/org/example/backend/timetable/domain/dto/TimetableReqDto.java
  backend/src/main/java/org/example/backend/timetable/domain/dto/TimetableResDto.java
  backend/src/main/java/org/example/backend/timetable/exception/TimetableExceptionType.java
  backend/src/main/java/org/example/backend/timetable/repository/TimetableRepository.java
  backend/src/main/java/org/example/backend/timetable/service/TimetableService.java
  backend/src/main/resources/data.sql
Labels: enhancement, 😄 BE

#189 [FE] 캘린더 리팩토링
  frontend/src/pages/SeminarRoom/Reservation.tsx
  frontend/src/pages/SeminarRoom/ReservationStyle.ts
Labels: enhancement, 🙂 FE

#191 [BE] user 에러 & 페이지 에러 수정
  backend/build.gradle
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/exception/BoardException.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/common/dto/PageRequestDto.java
  backend/src/main/java/org/example/backend/common/exception/ExceptionControllerAdvice.java
  backend/src/main/java/org/example/backend/common/exception/paging/InvalidPaginationParameterException.java
  backend/src/main/java/org/example/backend/common/exception/paging/InvalidPaginationParameterExceptionType.java
  backend/src/main/java/org/example/backend/user/repository/UserRepository.java
  backend/src/main/java/org/example/backend/user/service/UserService.java
  backend/src/main/resources/data.sql
Labels: 😄 BE, refactor

#187 [FE] [REFACTOR] [FIX] 교수, 논문 스크린샷 업로드
  frontend/src/components/Header/Header.tsx
  frontend/src/config/apiConfig.ts
  frontend/src/context/AuthContext.tsx
  frontend/src/pages/About/Faculty/ProfessorCard.tsx
  frontend/src/pages/About/Faculty/ProfessorCreate.tsx
  frontend/src/pages/About/Faculty/ProfessorEdit.tsx
  frontend/src/pages/About/Faculty/ProfessorEditStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeCreate.tsx
  frontend/src/pages/News/Thesis/ThesisCreate.tsx
  frontend/src/pages/News/Thesis/ThesisCreateStyle.ts
  frontend/src/pages/News/Thesis/ThesisEdit.tsx
Labels: 🙂 FE, refactor

#192 [BE] [REFACTOR] reqDto에서 파일 필드 숨김 및 Board category 필드를 필수에 추가
  backend/src/main/java/org/example/backend/board/domain/dto/BoardReqDto.java
  backend/src/main/java/org/example/backend/board/domain/entity/Category.java
  backend/src/main/java/org/example/backend/board/exception/BoardExceptionType.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/professor/domain/dto/professor/ProfessorReqDto.java
  backend/src/main/java/org/example/backend/thesis/domain/dto/ThesisReqDto.java
Labels: enhancement, 😄 BE

#196 [BE] [FEAT] 논문에 제목 필드 추가
  backend/src/main/java/org/example/backend/common/exception/ExceptionControllerAdvice.java
  backend/src/main/java/org/example/backend/common/exception/paging/CustomPageableHandler.java
  backend/src/main/java/org/example/backend/global/config/auth/CustomPageableHandlerConfig.java
  backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
  backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
  backend/src/main/java/org/example/backend/thesis/domain/dto/ThesisReqDto.java
  backend/src/main/java/org/example/backend/thesis/domain/entity/Thesis.java
  backend/src/main/java/org/example/backend/thesis/exception/ThesisExceptionType.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
  backend/src/main/resources/data.sql
Labels: enhancement, 😄 BE

#197 [BE] [REFACTOR] 논문 집권호 데이터 형식 수정 및 게시글 등록일 필드 추가
  backend/src/main/java/org/example/backend/board/domain/dto/BoardResDto.java
  backend/src/main/java/org/example/backend/board/domain/entity/Board.java
  backend/src/main/java/org/example/backend/common/utils/TimeParsingUtils.java
  backend/src/main/resources/data.sql
Labels: 😄 BE, refactor

#198 [FE] [FEAT] #194 교과과정 페이지 구현
  frontend/public/curriculum-2025.jpeg
  frontend/public/roadmap-2025.jpg
  frontend/src/AppContent.tsx
  frontend/src/components/Notfound/NotFound.tsx
  frontend/src/components/Notfound/NotFoundStyle.ts
  frontend/src/pages/Undergraduate/Curriculum/Curriculum.tsx
  frontend/src/pages/Undergraduate/Curriculum/CurriculumStyle.ts
Labels: enhancement, 🙂 FE

#202 [BE] [FEAT] 논문 resDto에 제목 필드 추가
  backend/src/main/java/org/example/backend/thesis/domain/dto/ThesisResDto.java
Labels: enhancement, 😄 BE

#201 [FE] 메인 페이지에서 특정 공지사항 클릭 시 해당 공지사항 페이지로 이동
  frontend/src/pages/Main/Main.tsx
Labels: enhancement, 🙂 FE

#203 [FE] 메인 페이지 논문 부분에 저자 대신 제목 표시
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/MainStyle.ts
Labels: enhancement, 🙂 FE

#207 [BE] refactor: pageDto
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
  backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
Labels: 😄 BE, refactor

#210 [FE] [FEAT] 게시글 정렬기능 추가
  frontend/public/index.html
  frontend/public/sejong-icon.svg
  frontend/src/AppContent.tsx
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Modal/styles/ModalStyles.ts
  frontend/src/config/apiConfig.ts
  frontend/src/context/AuthContext.tsx
  frontend/src/pages/Auth/AdminSignIn.tsx
  frontend/src/pages/Auth/SignInPage.tsx
  frontend/src/pages/Auth/SignInPageStyle.ts
  frontend/src/pages/Auth/SignInStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
  frontend/src/pages/News/NoticeBoard/NoticeBoardStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeCreate.tsx
  frontend/src/pages/News/NoticeBoard/hooks/useNoticeBoard.ts
  frontend/src/pages/News/NoticeBoard/types/notice.types.ts
Labels: enhancement, 🙂 FE, refactor

#211 [BE] refactor: createDate
  backend/src/main/java/org/example/backend/board/domain/dto/BoardResDto.java
  backend/src/main/java/org/example/backend/board/domain/entity/Board.java
Labels: 😄 BE, refactor

#213 [FE] 대학원 소개 페이지 구현
  frontend/src/AppContent.tsx
  frontend/src/pages/Graduate/GraduateOverview.tsx
  frontend/src/pages/Graduate/GraduateOverviewStyle.tsx
  frontend/src/pages/Main/Main.tsx
Labels: enhancement, 🙂 FE

#212 [FE] [FEAT] 게시판 리스트 등록일 정렬 기능 추가
  frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
  frontend/src/pages/News/NoticeBoard/hooks/useNoticeBoard.ts
  frontend/src/pages/News/NoticeBoard/types/notice.types.ts
Labels: 🙂 FE, refactor

#215 [BE] [REFACTOR] 게시글 생성일 필드 수정
  backend/src/main/java/org/example/backend/board/domain/dto/BoardResDto.java
Labels: 😄 BE, refactor

#217 [BE] [FEAT] 세미나 전체 조회 기능 추가
  backend/src/main/java/org/example/backend/seminar/controller/SeminarController.java
  backend/src/main/java/org/example/backend/seminar/service/SeminarService.java
Labels: enhancement, 😄 BE

#218 fix : 테스트 에러 수정
  backend/src/main/java/org/example/backend/reservation/controller/ReservationController.java
  backend/src/test/java/org/example/backend/ControllerTestSupport.java
  backend/src/test/java/org/example/backend/IntegrationTestSupport.java
  backend/src/test/java/org/example/backend/department/service/DepartmentServiceTest.java
  backend/src/test/java/org/example/backend/professor/controller/ProfessorControllerTest.java
  backend/src/test/java/org/example/backend/professor/service/ProfessorServiceTest.java
Labels: 😄 BE

#220 [BE] 예외처리 정리
  backend/build.gradle
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/domain/dto/BoardReqDto.java
  backend/src/main/java/org/example/backend/board/exception/BoardExceptionType.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/common/dto/PageRequestDto.java
  backend/src/main/java/org/example/backend/common/exception/ExceptionControllerAdvice.java
  backend/src/main/java/org/example/backend/common/exception/paging/InvalidPaginationParameterException.java
  backend/src/main/java/org/example/backend/common/exception/paging/InvalidPaginationParameterExceptionType.java
  backend/src/main/java/org/example/backend/department/domain/dto/Department/DepartmentReqDto.java
  backend/src/main/java/org/example/backend/department/exception/DepartmentExceptionType.java
  backend/src/main/java/org/example/backend/department/service/DepartmentService.java
  backend/src/main/java/org/example/backend/global/config/web/CorsMvcConfig.java
  backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
  backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
  backend/src/main/java/org/example/backend/professor/domain/dto/professor/ProfessorReqDto.java
  backend/src/main/java/org/example/backend/professor/exception/ProfessorExceptionType.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
  backend/src/main/java/org/example/backend/reservation/controller/ReservationController.java
  backend/src/main/java/org/example/backend/reservation/domain/RepetitionType.java
  backend/src/main/java/org/example/backend/reservation/domain/Reservation.java
  backend/src/main/java/org/example/backend/reservation/domain/dto/ReservationReqDto.java
  backend/src/main/java/org/example/backend/reservation/domain/dto/ReservationResDto.java
  backend/src/main/java/org/example/backend/reservation/exception/ReservationExceptionType.java
  backend/src/main/java/org/example/backend/reservation/service/ReservationService.java
  backend/src/main/java/org/example/backend/seminar/controller/SeminarController.java
  backend/src/main/java/org/example/backend/seminar/domain/dto/SeminarReqDto.java
  backend/src/main/java/org/example/backend/seminar/exception/SeminarExceptionType.java
  backend/src/main/java/org/example/backend/seminar/service/SeminarService.java
  backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
  backend/src/main/java/org/example/backend/thesis/domain/dto/ThesisReqDto.java
  backend/src/main/java/org/example/backend/thesis/exception/ThesisException.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
  backend/src/main/resources/data.sql
Labels: 😄 BE, refactor

#221 [FE] [FEAT] 학과 조직도 페이지 구현 (Google Maps)
  frontend/.env.development
  frontend/.env.production
  frontend/package.json
  frontend/src/AppContent.tsx
  frontend/src/config/apiConfig.ts
  frontend/src/constants/colors.ts
  frontend/src/context/AuthContext.tsx
  frontend/src/pages/About/Organization/Organization.tsx
  frontend/src/pages/About/Organization/OrganizationStyle.ts
  frontend/src/pages/Auth/SignInPage.tsx
  frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
  frontend/src/pages/News/NoticeBoard/NoticeCreate.tsx
  frontend/src/pages/News/NoticeBoard/NoticeDetail.tsx
  frontend/src/pages/News/NoticeBoard/NoticeDetailStyle.ts
  frontend/src/pages/News/NoticeBoard/types/notice.types.ts
Labels: enhancement, 🙂 FE

#224 [FE] 푸터 수정
  frontend/package-lock.json
  frontend/src/components/Footer/FooterStyle.ts
Labels: 🙂 FE, refactor

#226 [FE] 메인 페이지 색상 수정
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/MainStyle.ts
Labels: 🙂 FE, refactor

#230 feat : 배포 사이트 cors 추가
  backend/src/main/java/org/example/backend/global/config/auth/SecurityConfig.java
  backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
Labels: setting, 😄 BE
