Repository urinaner/sejong-dibb, pull requests merged in 2024-11, with the labels that each got.

#91 [BE] 게시판, 세미나, 논문 CRUD 기능 구현
  backend/docker-compose-dev.yml
  backend/src/main/generated/org/example/backend/admin/domain/mapper/SignInMapperImpl.java
  backend/src/main/generated/org/example/backend/board/domain/mapper/BoardMapperImpl.java
  backend/src/main/generated/org/example/backend/department/domain/mapper/DepartmentMapperImpl.java
  backend/src/main/generated/org/example/backend/professor/domain/mapper/ProfessorMapperImpl.java
  backend/src/main/generated/org/example/backend/seminar/domain/mapper/SeminarMapperImpl.java
  backend/src/main/generated/org/example/backend/thesis/domain/mapper/ThesisMapperImpl.java
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/domain/dto/BoardReqDto.java
  backend/src/main/java/org/example/backend/board/domain/dto/BoardResDto.java
  backend/src/main/java/org/example/backend/board/domain/entity/Board.java
  backend/src/main/java/org/example/backend/board/domain/mapper/BoardMapper.java
  backend/src/main/java/org/example/backend/board/exception/BoardException.java
  backend/src/main/java/org/example/backend/board/exception/BoardExceptionType.java
  backend/src/main/java/org/example/backend/board/repository/BoardRepository.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/seminar/controller/SeminarController.java
  backend/src/main/java/org/example/backend/seminar/domain/dto/SeminarReqDto.java
  backend/src/main/java/org/example/backend/seminar/domain/dto/SeminarResDto.java
  backend/src/main/java/org/example/backend/seminar/domain/entity/Seminar.java
  backend/src/main/java/org/example/backend/seminar/domain/mapper/SeminarMapper.java
  backend/src/main/java/org/example/backend/seminar/exception/SeminarException.java
  backend/src/main/java/org/example/backend/seminar/exception/SeminarExceptionType.java
  backend/src/main/java/org/example/backend/seminar/repository/SeminarRepository.java
  backend/src/main/java/org/example/backend/seminar/service/SeminarService.java
  backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
  backend/src/main/java/org/example/backend/thesis/domain/dto/ThesisReqDto.java
  backend/src/main/java/org/example/backend/thesis/domain/dto/ThesisResDto.java
  backend/src/main/java/org/example/backend/thesis/domain/entity/Thesis.java
  backend/src/main/java/org/example/backend/thesis/domain/mapper/ThesisMapper.java
  backend/src/main/java/org/example/backend/thesis/exception/ThesisException.java
  backend/src/main/java/org/example/backend/thesis/exception/ThesisExceptionType.java
  backend/src/main/java/org/example/backend/thesis/repository/ThesisRepository.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
  backend/src/test/java/org/example/backend/professor/service/ProfessorServiceTest.java
Labels: enhancement, 😄 BE

#95 chore: 더미데이터 추가
  backend/src/main/resources/data.sql
Labels: setting

#88 [FE] 헤더 레이아웃 반응형 로직 개선
  frontend/src/App.tsx
  frontend/src/AppContent.tsx
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/NavItem.tsx
  frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
  frontend/src/pages/News/NoticeBoard/NoticeBoardStyle.ts
  frontend/src/styles/HeaderStyles.ts
Labels: enhancement, 🙂 FE

#92 [BE] refactor: 테스트 환경 통합
  backend/src/test/java/org/example/backend/BackendApplicationTests.java
  backend/src/test/java/org/example/backend/ControllerTestSupport.java
  backend/src/test/java/org/example/backend/IntegrationTestSupport.java
  backend/src/test/java/org/example/backend/department/controller/DepartmentControllerTest.java
  backend/src/test/java/org/example/backend/department/repository/DepartmentRepositoryTest.java
  backend/src/test/java/org/example/backend/department/service/DepartmentServiceTest.java
  backend/src/test/java/org/example/backend/professor/controller/ProfessorControllerTest.java
  backend/src/test/java/org/example/backend/professor/domain/mapper/ProfessorMapperTest.java
  backend/src/test/java/org/example/backend/professor/repository/ProfessorRepositoryTest.java
  backend/src/test/java/org/example/backend/professor/service/ProfessorServiceTest.java
Labels: 😄 BE, refactor

#97 [BE] 보드 페이징
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/professor/domain/dto/ResponseDto.java
Labels: enhancement, 😄 BE

#100 [FE] 메인 페이지 바로가기 링크 수정
  frontend/src/pages/Main/Main.tsx
Labels: 🙂 FE, refactor

#104 Feature/85
  frontend/src/AppContent.tsx
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/config/apiConfig.ts
  frontend/src/context/AuthContext.tsx
  frontend/src/pages/Auth/SignIn.tsx
  frontend/src/pages/Auth/SignInStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
  frontend/src/pages/News/NoticeBoard/NoticeBoardStyle.ts
  frontend/src/styles/SignInStyle.ts
  frontend/src/types/board.ts
Labels: enhancement, 🙂 FE

#106 [FE] 사용자 아이콘 추가 및 로그아웃 기능 AuthContext 개선
  frontend/.env.development
  frontend/src/assets/images/user-icon.svg
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Footer/FooterStyle.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/HeaderStyles.ts
  frontend/src/components/Header/NavItem.tsx
  frontend/src/components/Modal/Modal.tsx
  frontend/src/context/AuthContext.tsx
  frontend/src/context/ModalStyle.ts
  frontend/src/pages/Auth/SignInStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
Labels: enhancement, 🙂 FE

#102 [BE] 교수, 논문 페이징
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/domain/entity/Board.java
  backend/src/main/java/org/example/backend/board/domain/entity/Category.java
  backend/src/main/java/org/example/backend/common/exception/dto/ResponseDto.java
  backend/src/main/java/org/example/backend/global/config/SecurityConfig.java
  backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
  backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
  backend/src/main/resources/data.sql
Labels: enhancement, 😄 BE

#111 feat(docker-compose): 더미 데이터 경로 설정
  backend/docker-compose-dev.yml
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: 😄 BE, docker

#110 도커 문제 해결
  backend/backup.sql
  backend/docker-compose-dev.yml
  backend/src/main/resources/application-docker-dev.yml
  backend/src/main/resources/data.sql
Labels: bug, 😄 BE, docker

#114 [FE] 모달 렌더링 버그
  frontend/src/context/ModalStyle.ts
Labels: bug, 🙂 FE

#120 [FE] 바용소식 - 공지사항 리스트 조회, 게시글 작성, 상세 페이지 기능 구현
  frontend/.env.development
  frontend/package-lock.json
  frontend/package.json
  frontend/src/AppContent.tsx
  frontend/src/config/apiConfig.ts
  frontend/src/context/AuthContext.tsx
  frontend/src/global.d.ts
  frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
  frontend/src/pages/News/NoticeBoard/NoticeBoardStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeCreate.tsx
  frontend/src/pages/News/NoticeBoard/NoticeCreateStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeDetail.tsx
  frontend/src/pages/News/NoticeBoard/NoticeDetailStyle.ts
  frontend/src/react-quill.d.ts
  frontend/src/types/board.ts
Labels: enhancement, 🙂 FE

#123 [FE] 메인페이지 api 연결
  frontend/src/config/apiConfig.ts
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/MainStyle.ts
Labels: enhancement, 🙂 FE

#124 [FE] [FEAT] 교수 CRUD 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/public/professor_example.jpg
  frontend/src/AppContent.tsx
  frontend/src/common/Button/Button.tsx
  frontend/src/common/Button/ButtonGroup.tsx
  frontend/src/common/Button/types.ts
  frontend/src/config/apiConfig.ts
  frontend/src/pages/About/Faculty.tsx
  frontend/src/pages/About/Faculty/FacultyStyle.ts
  frontend/src/pages/About/Faculty/Professor.tsx
  frontend/src/pages/About/Faculty/ProfessorCard.tsx
  frontend/src/pages/About/Faculty/ProfessorCreate.tsx
  frontend/src/pages/About/Faculty/ProfessorDetail.tsx
  frontend/src/pages/About/Faculty/ProfessorDetailStyle.ts
  frontend/src/pages/About/Faculty/ProfessorEdit.tsx
  frontend/src/pages/About/Faculty/ProfessorEditStyle.ts
  frontend/src/pages/About/Faculty/ProfileSection.tsx
  frontend/src/pages/About/Faculty/ProfileSectionStyle.ts
  frontend/src/pages/About/Faculty/TabSection.tsx
  frontend/src/pages/About/Faculty/TabSectionStyle.ts
  frontend/src/pages/About/Faculty/tabs/BasicInfo.tsx
  frontend/src/pages/About/Faculty/tabs/Publications.tsx
  frontend/src/pages/About/Faculty/tabs/PublicationsStyle.ts
  frontend/src/pages/About/FacultyStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
  frontend/src/pages/News/NoticeBoard/NoticeBoardStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeCreateStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeDetail.tsx
  frontend/src/pages/News/NoticeBoard/NoticeDetailStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeEdit.tsx
  frontend/src/types/professor.ts
Labels: enhancement, 🙂 FE

#130 [BE] 기본 CRUD 수정사항 점검
  backend/build.gradle
  backend/src/main/generated/org/example/backend/admin/domain/mapper/SignInMapperImpl.java
  backend/src/main/generated/org/example/backend/board/domain/mapper/BoardMapperImpl.java
  backend/src/main/generated/org/example/backend/department/domain/mapper/DepartmentMapperImpl.java
  backend/src/main/generated/org/example/backend/professor/domain/mapper/ProfessorMapperImpl.java
  backend/src/main/generated/org/example/backend/seminar/domain/mapper/SeminarMapperImpl.java
  backend/src/main/generated/org/example/backend/thesis/domain/mapper/ThesisMapperImpl.java
  backend/src/main/java/org/example/backend/admin/domain/entity/Admin.java
  backend/src/main/java/org/example/backend/common/exception/ExceptionControllerAdvice.java
  backend/src/main/java/org/example/backend/department/controller/DepartmentController.java
  backend/src/main/java/org/example/backend/department/domain/entity/Department.java
  backend/src/main/java/org/example/backend/department/service/DepartmentService.java
  backend/src/main/java/org/example/backend/global/config/SecurityConfig.java
  backend/src/main/java/org/example/backend/global/config/SjConfig.java
  backend/src/main/java/org/example/backend/professor/domain/entity/Professor.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
  backend/src/main/java/org/example/backend/thesis/domain/entity/Thesis.java
  backend/src/main/java/org/example/backend/user/controller/UserController.java
  backend/src/main/java/org/example/backend/user/service/UserService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/org/example/backend/SjTest.java
  backend/src/test/java/org/example/backend/department/controller/DepartmentControllerTest.java
  backend/src/test/java/org/example/backend/department/repository/DepartmentRepositoryTest.java
  backend/src/test/java/org/example/backend/professor/domain/mapper/ProfessorMapperTest.java
  backend/src/test/java/org/example/backend/professor/repository/ProfessorRepositoryTest.java
  backend/src/test/java/org/example/backend/professor/service/ProfessorServiceTest.java
Labels: bug, 😄 BE

#133 [BE] 게시판 필터링 기능 추가
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/domain/entity/Category.java
  backend/src/main/java/org/example/backend/board/repository/BoardRepository.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
Labels: enhancement, 😄 BE

#139 [BE] 논문, 교수별 조회 로직 추가
  backend/src/main/generated/org/example/backend/thesis/domain/mapper/ThesisMapperImpl.java
  backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
  backend/src/main/java/org/example/backend/thesis/repository/ThesisRepository.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
Labels: enhancement, 😄 BE

#140 [FE] 세미나실 예약 페이지 UI 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/public/seminarRoom1.jpg
  frontend/src/AppContent.tsx
  frontend/src/pages/SeminarRoom/Reservation.tsx
  frontend/src/pages/SeminarRoom/ReservationStyle.ts
Labels: enhancement, 🙂 FE

#137 [BE] 정확한 에러 메세지 출력
  backend/.gitignore
  backend/src/main/generated/org/example/backend/board/domain/mapper/BoardMapperImpl.java
  backend/src/main/generated/org/example/backend/department/domain/mapper/DepartmentMapperImpl.java
  backend/src/main/java/org/example/backend/admin/exception/AdminExceptionType.java
  backend/src/main/java/org/example/backend/admin/service/AdminService.java
  backend/src/main/java/org/example/backend/board/domain/dto/BoardReqDto.java
  backend/src/main/java/org/example/backend/board/domain/dto/BoardResDto.java
  backend/src/main/java/org/example/backend/board/domain/mapper/BoardMapper.java
  backend/src/main/java/org/example/backend/board/exception/BoardExceptionType.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/common/exception/ExceptionControllerAdvice.java
  backend/src/main/java/org/example/backend/common/exception/paging/CustomPageableHandler.java
  backend/src/main/java/org/example/backend/common/exception/paging/InvalidPaginationParameterException.java
  backend/src/main/java/org/example/backend/common/exception/paging/InvalidPaginationParameterExceptionType.java
  backend/src/main/java/org/example/backend/department/exception/DepartmentExceptionType.java
  backend/src/main/java/org/example/backend/department/service/DepartmentService.java
  backend/src/main/java/org/example/backend/global/config/CustomAuthenticationFailureHandler.java
  backend/src/main/java/org/example/backend/global/config/CustomPageableHandlerConfig.java
  backend/src/main/resources/application.yml
Labels: 😄 BE, refactor

#148 [FE] [FEAT] 라우트 가드 기능 구현
  frontend/src/AppContent.tsx
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/HeaderStyles.ts
  frontend/src/components/ProtectedRoute/ProtectedRoute.tsx
  frontend/src/config/apiConfig.ts
  frontend/src/context/AuthContext.tsx
  frontend/src/hooks/useAuth.tsx
  frontend/src/pages/Auth/AdminSignIn.tsx
Labels: enhancement, 🙂 FE

#147 [BE] Mapper -> 정적 펙토리 적용
  backend/build.gradle
  backend/src/main/java/org/example/backend/admin/controller/AdminController.java
  backend/src/main/java/org/example/backend/admin/domain/entity/Admin.java
  backend/src/main/java/org/example/backend/admin/domain/mapper/AdminMapper.java
  backend/src/main/java/org/example/backend/admin/domain/mapper/SignInMapper.java
  backend/src/main/java/org/example/backend/admin/service/AdminService.java
  backend/src/main/java/org/example/backend/board/domain/dto/BoardReqDto.java
  backend/src/main/java/org/example/backend/board/domain/dto/BoardResDto.java
  backend/src/main/java/org/example/backend/board/domain/entity/Board.java
  backend/src/main/java/org/example/backend/board/domain/mapper/BoardMapper.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/department/domain/dto/Department/DepartmentReqDto.java
  backend/src/main/java/org/example/backend/department/domain/dto/Department/DepartmentResDto.java
  backend/src/main/java/org/example/backend/department/domain/entity/Department.java
  backend/src/main/java/org/example/backend/department/domain/mapper/DepartmentMapper.java
  backend/src/main/java/org/example/backend/department/service/DepartmentService.java
  backend/src/main/java/org/example/backend/global/config/BaseEntity.java
  backend/src/main/java/org/example/backend/global/config/CentralMapperConfig.java
  backend/src/main/java/org/example/backend/global/config/JpaAuditingConfig.java
  backend/src/main/java/org/example/backend/jwt/JWTFilter.java
  backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
  backend/src/main/java/org/example/backend/professor/domain/dto/professor/ProfessorReqDto.java
  backend/src/main/java/org/example/backend/professor/domain/dto/professor/ProfessorResDto.java
  backend/src/main/java/org/example/backend/professor/domain/entity/Professor.java
  backend/src/main/java/org/example/backend/professor/domain/mapper/ProfessorMapper.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
  backend/src/main/java/org/example/backend/seminar/domain/dto/SeminarReqDto.java
  backend/src/main/java/org/example/backend/seminar/domain/dto/SeminarResDto.java
  backend/src/main/java/org/example/backend/seminar/domain/entity/Seminar.java
  backend/src/main/java/org/example/backend/seminar/domain/mapper/SeminarMapper.java
  backend/src/main/java/org/example/backend/seminar/service/SeminarService.java
  backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
  backend/src/main/java/org/example/backend/thesis/domain/dto/ThesisReqDto.java
  backend/src/main/java/org/example/backend/thesis/domain/dto/ThesisResDto.java
  backend/src/main/java/org/example/backend/thesis/domain/entity/Thesis.java
  backend/src/main/java/org/example/backend/thesis/domain/mapper/ThesisMapper.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/org/example/backend/IntegrationTestSupport.java
  backend/src/test/java/org/example/backend/department/controller/DepartmentControllerTest.java
  backend/src/test/java/org/example/backend/department/repository/DepartmentRepositoryTest.java
  backend/src/test/java/org/example/backend/department/service/DepartmentServiceTest.java
  backend/src/test/java/org/example/backend/professor/controller/ProfessorControllerTest.java
  backend/src/test/java/org/example/backend/professor/domain/mapper/ProfessorMapperTest.java
  backend/src/test/java/org/example/backend/professor/repository/ProfessorRepositoryTest.java
  backend/src/test/java/org/example/backend/professor/service/ProfessorServiceTest.java
Labels: 😄 BE, refactor

#152 [BE] 이미지 업로드 기능 구현
  backend/build.gradle
  backend/src/main/generated/org/example/backend/.DS_Store
  backend/src/main/generated/org/example/backend/admin/.DS_Store
  backend/src/main/generated/org/example/backend/admin/domain/mapper/AdminMapperImpl.java
  backend/src/main/generated/org/example/backend/admin/domain/mapper/SignInMapperImpl.java
  backend/src/main/generated/org/example/backend/admin/mapper/.DS_Store
  backend/src/main/generated/org/example/backend/board/domain/mapper/BoardMapperImpl.java
  backend/src/main/generated/org/example/backend/department/domain/mapper/DepartmentMapperImpl.java
  backend/src/main/generated/org/example/backend/professor/domain/mapper/ProfessorMapperImpl.java
  backend/src/main/generated/org/example/backend/seminar/domain/mapper/SeminarMapperImpl.java
  backend/src/main/generated/org/example/backend/thesis/domain/mapper/ThesisMapperImpl.java
  backend/src/main/java/org/example/backend/global/config/AWSConfiguration.java
  backend/src/main/java/org/example/backend/global/config/S3Uploader.java
  backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
  backend/src/main/java/org/example/backend/professor/domain/dto/professor/ProfessorReqDto.java
  backend/src/main/java/org/example/backend/professor/domain/entity/Professor.java
  backend/src/main/java/org/example/backend/professor/exception/ProfessorExceptionType.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
  backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
  backend/src/main/java/org/example/backend/thesis/domain/dto/ThesisReqDto.java
  backend/src/main/java/org/example/backend/thesis/domain/entity/Thesis.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
  backend/src/main/resources/data.sql
Labels: enhancement, 😄 BE

#162 [BE] User, Reservation, SeminarRoom 엔티티 설계
  backend/src/main/java/org/example/backend/global/config/S3Uploader.java
  backend/src/main/java/org/example/backend/reservation/domain/Reservation.java
  backend/src/main/java/org/example/backend/reservation/domain/ReservationPurpose.java
  backend/src/main/java/org/example/backend/reservation/domain/ReservationStatus.java
  backend/src/main/java/org/example/backend/seminarRoom/domain/SeminarRoom.java
  backend/src/main/java/org/example/backend/user/domain/entity/User.java
Labels: enhancement, 😄 BE

#159 [FE] 푸터 반응형 디자인 레이아웃 개선
  frontend/src/components/Footer/FooterStyle.ts
Labels: 🙂 FE, refactor

#161 [FE] 메인 페이지 반응형 디자인 적용
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/MainStyle.ts
Labels: enhancement, 🙂 FE

#167 [BE] 빌드 에러 수정
  backend/src/main/java/org/example/backend/seminarRoom/domain/SeminarRoom.java
Labels: bug, 😄 BE

#169 [BE] 세미나실, 시간표 CRUD 설계
  backend/src/main/java/org/example/backend/seminarRoom/domain/SeminarRoom.java
  backend/src/main/java/org/example/backend/seminarRoom/domain/controller/SeminarRoomController.java
  backend/src/main/java/org/example/backend/seminarRoom/domain/dto/SeminarRoomReqDto.java
  backend/src/main/java/org/example/backend/seminarRoom/domain/dto/SeminarRoomResDto.java
  backend/src/main/java/org/example/backend/seminarRoom/exception/SeminarRoomException.java
  backend/src/main/java/org/example/backend/seminarRoom/exception/SeminarRoomExceptionType.java
  backend/src/main/java/org/example/backend/seminarRoom/repository/SeminarRoomRepository.java
  backend/src/main/java/org/example/backend/seminarRoom/service/SeminarRoomService.java
  backend/src/main/java/org/example/backend/timetable/controller/TimetableController.java
  backend/src/main/java/org/example/backend/timetable/domain/Timetable.java
  backend/src/main/java/org/example/backend/timetable/domain/WeekDay.java
  backend/src/main/java/org/example/backend/timetable/domain/dto/TimetableReqDto.java
  backend/src/main/java/org/example/backend/timetable/domain/dto/TimetableResDto.java
  backend/src/main/java/org/example/backend/timetable/exception/TimetableException.java
  backend/src/main/java/org/example/backend/timetable/exception/TimetableExceptionType.java
  backend/src/main/java/org/example/backend/timetable/repository/TimetableRepository.java
  backend/src/main/java/org/example/backend/timetable/service/TimetableService.java
  backend/src/main/resources/data.sql
Labels: enhancement, 😄 BE

#168 [BE] User 기본 CRUD 기능 구현
  backend/backup.sql
  backend/src/main/java/org/example/backend/admin/exception/AdminExceptionType.java
  backend/src/main/java/org/example/backend/seminar/controller/SeminarController.java
  backend/src/main/java/org/example/backend/user/controller/UserController.java
  backend/src/main/java/org/example/backend/user/domain/dto/UserReqDto.java
  backend/src/main/java/org/example/backend/user/domain/dto/UserResDto.java
  backend/src/main/java/org/example/backend/user/domain/entity/User.java
  backend/src/main/java/org/example/backend/user/exception/UserException.java
  backend/src/main/java/org/example/backend/user/exception/UserExceptionType.java
  backend/src/main/java/org/example/backend/user/repository/UserRepository.java
  backend/src/main/java/org/example/backend/user/service/UserService.java
  backend/src/main/resources/data.sql
Labels: enhancement, 😄 BE

#171 [BE] 교수, 논문 update 기능에 파일 형식 추가
  backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
  backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
Labels: enhancement, 😄 BE

#173 [BE] Board 파일 업로드 기능 추가
  backend/backup.sql
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/domain/dto/BoardReqDto.java
  backend/src/main/java/org/example/backend/board/domain/dto/BoardResDto.java
  backend/src/main/java/org/example/backend/board/domain/entity/Board.java
  backend/src/main/java/org/example/backend/board/exception/BoardExceptionType.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/global/config/StringListConverter.java
  backend/src/main/resources/data.sql
Labels: enhancement, 😄 BE

#175 [BE] 예약 구현
  backend/backup.sql
Labels: enhancement, 😄 BE

#178 [BE] [REFACTOR] 파일 필드를 필수 필드에서 제외
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
  backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
Labels: 😄 BE, refactor

#181 [BE] AOP 적용
  backend/src/main/java/org/example/backend/admin/service/AdminService.java
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/domain/entity/Board.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/common/domain/BaseEntity.java
  backend/src/main/java/org/example/backend/common/dto/ResponseDto.java
  backend/src/main/java/org/example/backend/common/exception/auth/AuthException.java
  backend/src/main/java/org/example/backend/common/exception/auth/AuthExceptionType.java
  backend/src/main/java/org/example/backend/department/domain/entity/Department.java
  backend/src/main/java/org/example/backend/global/aop/AuthAdmin.java
  backend/src/main/java/org/example/backend/global/aop/AuthAdminResolver.java
  backend/src/main/java/org/example/backend/global/aop/AuthUser.java
  backend/src/main/java/org/example/backend/global/aop/AuthUserResolver.java
  backend/src/main/java/org/example/backend/global/config/auth/CustomAuthenticationFailureHandler.java
  backend/src/main/java/org/example/backend/global/config/auth/CustomPageableHandlerConfig.java
  backend/src/main/java/org/example/backend/global/config/auth/SecurityConfig.java
  backend/src/main/java/org/example/backend/global/config/aws/AWSConfiguration.java
  backend/src/main/java/org/example/backend/global/config/aws/S3Uploader.java
  backend/src/main/java/org/example/backend/global/config/jpa/JpaAuditingConfig.java
  backend/src/main/java/org/example/backend/global/config/sj/SjConfig.java
  backend/src/main/java/org/example/backend/global/config/swagger/SwaggerConfig.java
  backend/src/main/java/org/example/backend/global/config/web/CorsMvcConfig.java
  backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
  backend/src/main/java/org/example/backend/global/util/StringListConverter.java
  backend/src/main/java/org/example/backend/jwt/JWTUtil.java
  backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
  backend/src/main/java/org/example/backend/reservation/domain/Reservation.java
  backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
  backend/src/main/java/org/example/backend/user/controller/UserController.java
  backend/src/main/java/org/example/backend/user/service/UserService.java
Labels: enhancement, 😄 BE, refactor
