Repository urinaner/sejong-dibb, pull requests merged in 2025-04, with the labels that each got.

#460 [FE] SEO 관련 파일 생성
  frontend/public/google7b8b29cb66f52214.html
  frontend/public/robots.txt
  frontend/public/sitemap.xml
Labels: 🙂 FE

#461 #459 feat: Google Search Console 설정 파일 업로드
  frontend/src/routes/AppRoutes.tsx
Labels: 🙂 FE

#458 [BE] 교과과목 도메인 생성
  backend/src/main/java/org/example/backend/course/controller/CourseController.java
  backend/src/main/java/org/example/backend/course/domain/dto/req/BSCourseReqDto.java
  backend/src/main/java/org/example/backend/course/domain/dto/req/CourseReqDto.java
  backend/src/main/java/org/example/backend/course/domain/dto/req/MSCourseReqDto.java
  backend/src/main/java/org/example/backend/course/domain/dto/res/BSCourseResDto.java
  backend/src/main/java/org/example/backend/course/domain/dto/res/CourseResDto.java
  backend/src/main/java/org/example/backend/course/domain/dto/res/CourseResDtoFactory.java
  backend/src/main/java/org/example/backend/course/domain/dto/res/MSCourseResDto.java
  backend/src/main/java/org/example/backend/course/domain/entity/BSCourse.java
  backend/src/main/java/org/example/backend/course/domain/entity/Course.java
  backend/src/main/java/org/example/backend/course/domain/entity/CourseType.java
  backend/src/main/java/org/example/backend/course/domain/entity/MSCourse.java
  backend/src/main/java/org/example/backend/course/exception/CourseException.java
  backend/src/main/java/org/example/backend/course/exception/CourseExceptionType.java
  backend/src/main/java/org/example/backend/course/repository/CourseRepository.java
  backend/src/main/java/org/example/backend/course/service/CourseService.java
  backend/src/main/java/org/example/backend/global/config/auth/SecurityConfig.java
  backend/src/main/resources/db/migration/V20250403_01__create_course_bs_ms_table.sql
Labels: enhancement, 😄 BE

#468 [FE] SEO 속성 및 테스트 도구 연결
  frontend/public/index.html
Labels: 🙂 FE

#471 #470 feat: 학부과정, 대학원 교과과정 컴포넌트 추가 및 연동
  frontend/.gitignore
  frontend/package.json
  frontend/src/components/Course/CourseManagement.tsx
  frontend/src/components/Course/components/CourseForm.tsx
  frontend/src/components/Course/components/CourseTable.tsx
  frontend/src/components/Course/components/CourseTableRow.tsx
  frontend/src/components/Course/hooks/useCourse.ts
  frontend/src/components/Course/styles/CourseStyles.ts
  frontend/src/components/Course/types/course.types.ts
  frontend/src/config/apiConfig.ts
  frontend/src/pages/Graduate/GraduateCurriculum.tsx
  frontend/src/pages/Undergraduate/Curriculum/Curriculum.tsx
Labels: enhancement, 🙂 FE
