Repository urinaner/sejong-dibb, pull requests merged in 2025-02, with the labels that each got.

#317 [BE] logging 기능 추가
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/common/logging/Logging.java
  backend/src/main/java/org/example/backend/common/logging/LoggingAspect.java
Labels: enhancement, 😄 BE

#326 [BE] [REFACTOR] admin 코드 정리
  backend/src/main/java/org/example/backend/users/controller/admin/AdminController.java
  backend/src/main/java/org/example/backend/users/controller/member/MemberController.java
  backend/src/main/java/org/example/backend/users/domain/dto/LoginReqDto.java
  backend/src/main/java/org/example/backend/users/domain/dto/member/SjLoginReq.java
  backend/src/main/java/org/example/backend/users/domain/entity/Users.java
  backend/src/main/java/org/example/backend/users/repository/UsersRepository.java
  backend/src/main/java/org/example/backend/users/service/AdminService.java
  backend/src/main/java/org/example/backend/users/service/CustomUserDetailsService.java
  backend/src/main/java/org/example/backend/users/service/MemberService.java
  backend/src/test/java/org/example/backend/SjTest.java
Labels: 😄 BE, refactor

#324 [BE][FEAT] 뉴스, 공지, 세미나, 논문 검색기능
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/repository/BoardRepository.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/news/controller/NewsController.java
  backend/src/main/java/org/example/backend/news/repository/NewsRepository.java
  backend/src/main/java/org/example/backend/news/service/NewsService.java
  backend/src/main/java/org/example/backend/professor/domain/entity/Professor.java
  backend/src/main/java/org/example/backend/seminar/controller/SeminarController.java
  backend/src/main/java/org/example/backend/seminar/repository/SeminarRepository.java
  backend/src/main/java/org/example/backend/seminar/service/SeminarService.java
  backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
  backend/src/main/java/org/example/backend/thesis/repository/ThesisRepository.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
Labels: enhancement, 😄 BE

#328 [BE][FEAT] 관리자 비밀번호 수정 기능 구현
  backend/src/main/java/org/example/backend/users/controller/admin/AdminController.java
  backend/src/main/java/org/example/backend/users/domain/dto/admin/AdminResDto.java
  backend/src/main/java/org/example/backend/users/service/AdminService.java
Labels: enhancement, 😄 BE

#331 user통합(admin, member)에 따른 data.sql 수정
  backend/src/main/resources/data.sql
Labels: bug, 😄 BE

#321 #313 fix: 프로덕션 모드 사용하도록 Dockerfile 수정
  .github/workflows/main.yml
  frontend/.eslintrc.json
  frontend/Dockerfile
  frontend/package.json
  frontend/src/config/apiConfig.ts
  frontend/src/hooks/queries/useNews.ts
  frontend/src/hooks/queries/useNotice.ts
  frontend/src/hooks/queries/useProfessor.ts
  frontend/src/hooks/queries/useSeminar.ts
  frontend/src/hooks/queries/useThesis.ts
Labels: bug

#333 [BE][FEAT] 멤버 더미 데이터 추가
  backend/src/main/resources/data.sql
Labels: enhancement, 😄 BE

#335 [FE] [FEAT] 로그인 상태관리 refresh, 탑헤더
  frontend/.env.development
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Header/HeaderStyle.ts
  frontend/src/components/Header/TopHeader.tsx
  frontend/src/components/NewsSlider/NewsSliderStyle.ts
  frontend/src/components/layout/PageLayout.tsx
  frontend/src/config/apiConfig.ts
  frontend/src/context/AuthContext.tsx
  frontend/src/pages/Auth/SignInPage.tsx
  frontend/src/pages/Auth/SignInPageStyle.ts
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/MainStyle.ts
Labels: enhancement, 🙂 FE, refactor

#337 [FIX] [FE] 프로덕션 환경 uri 중복
  frontend/src/AppContent.tsx
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/ProtectedRoute/ProtectedRoute.tsx
  frontend/src/config/apiConfig.ts
  frontend/src/context/AuthContext.tsx
  frontend/src/pages/Admin/ChangeAdminPassword/ChangeAdminPassword.tsx
Labels: bug, 🙂 FE

#339 [FE][REFACTOR] 엑세스, 리프레시 토큰 쿠키저장 로직으로 리펙토링
  frontend/package.json
  frontend/src/context/AuthContext.tsx
Labels: setting, 🙂 FE, refactor

#346 [BE] [FEAT] jwt에서 유저 정보 가져오는 기능 구현
  backend/src/main/java/org/example/backend/jwt/JWTFilter.java
  backend/src/main/java/org/example/backend/users/controller/admin/AdminController.java
Labels: enhancement, 😄 BE

#350 [BE][FEAT] 멤버 로그인 바이오융합학과로 제한 기능 구현
  backend/src/main/java/org/example/backend/users/exception/member/MemberException.java
  backend/src/main/java/org/example/backend/users/exception/member/MemberExceptionType.java
  backend/src/main/java/org/example/backend/users/service/MemberService.java
Labels: enhancement, 😄 BE

#343 [BE] [BUG] 게시판 생성 후 접근 불가 && 파일 첨부 실패
  backend/src/main/java/org/example/backend/board/domain/entity/Board.java
  backend/src/main/java/org/example/backend/common/domain/BaseEntity.java
  backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
  backend/src/main/java/org/example/backend/news/domain/dto/NewsResDto.java
  backend/src/main/resources/data.sql
Labels: bug, 😄 BE

#351 [BE][FEAT] 관리자 기존 비밀번호 검토 API 기능 구현
  backend/src/main/java/org/example/backend/users/controller/admin/AdminController.java
Labels: bug, 😄 BE

#349 [BE] 유저 ArgumentResolver 구현 & 예약 적용
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/common/aop/auth/LoginArgumentResolver.java
  backend/src/main/java/org/example/backend/common/aop/auth/LoginUser.java
  backend/src/main/java/org/example/backend/common/aop/logging/Logging.java
  backend/src/main/java/org/example/backend/common/aop/logging/LoggingAspect.java
  backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
  backend/src/main/java/org/example/backend/reservation/controller/ReservationController.java
  backend/src/main/java/org/example/backend/reservation/domain/Reservation.java
  backend/src/main/java/org/example/backend/reservation/domain/dto/ReservationResDto.java
  backend/src/main/java/org/example/backend/reservation/service/ReservationService.java
Labels: enhancement, 😄 BE

#352 [FE][FEAT] 관리자 비밀번호 변경 페이지 구현
  frontend/public/haru.png
  frontend/public/haru_organization.png
  frontend/src/AppContent.tsx
  frontend/src/components/Banner/PageBanner/PageBanner.tsx
  frontend/src/components/Header/Navigation/Navigation.tsx
  frontend/src/components/Header/constants.ts
  frontend/src/constants/pageContents.ts
  frontend/src/context/AuthContext.tsx
  frontend/src/pages/About/AboutStyle.ts
  frontend/src/pages/About/StudentCouncil/StudentCouncil.tsx
  frontend/src/pages/About/StudentCouncil/StudentCouncilStyle.ts
  frontend/src/pages/Admin/ChangeAdminPassword/ChangeAdminPassword.tsx
Labels: enhancement, 🙂 FE

#356 [Fix/353] FE 버그 수정
  frontend/package.json
  frontend/src/config/apiConfig.ts
  frontend/src/hooks/queries/useNews.ts
  frontend/src/hooks/queries/useThesis.ts
  frontend/src/pages/Main/components/NewsSection/index.tsx
  frontend/src/pages/News/News/News.tsx
  frontend/src/pages/News/News/NewsCreateStyle.ts
  frontend/src/pages/News/News/NewsDetail.tsx
  frontend/src/pages/News/News/NewsDetailStyle.ts
  frontend/src/pages/News/News/NewsStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeBoardStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeDetailStyle.ts
  frontend/src/pages/News/Thesis/ThesisCreate.tsx
  frontend/src/pages/News/Thesis/ThesisDetail.tsx
  frontend/src/pages/News/Thesis/ThesisEdit.tsx
  frontend/src/pages/News/Thesis/ThesisForm.tsx
  frontend/src/pages/News/Thesis/ThesisList.tsx
Labels: bug, 🙂 FE

#359 [FE][FIX] 로그인 실패 시 (401에러 응답시 login 리다이렉트 로직 제거)
  frontend/src/config/apiConfig.ts
  frontend/src/context/AuthContext.tsx
  frontend/src/pages/Auth/SignInPage.tsx
Labels: bug, 🙂 FE

#358 [BE] 관리자 계정만 뉴스, 공지사항, 세미나, 논문 생성/수정/삭제 권한 허용
  backend/src/main/java/org/example/backend/global/config/auth/SecurityConfig.java
  backend/src/main/resources/data.sql
Labels: setting, 😄 BE

#362 [BE][REFACTOR] 멤버 비밀번호 저장 방식 수정 (DB 미저장 처리)
  backend/src/main/java/org/example/backend/users/service/MemberService.java
Labels: 😄 BE, refactor

#367 [FIX] Eslint Prettier 문제 해결 및 재배포
  frontend/README.md
  frontend/src/components/Modal/templates/TermsModal.tsx
  frontend/src/index.css
  frontend/tsconfig.json
Labels: bug, 🙂 FE

#368 [FE] [CHORE] PM 요구사항 반영
  frontend/src/constants/pageContents.ts
  frontend/src/pages/About/StudentCouncil/StudentCouncil.tsx
Labels: setting

#371 refactor: cors해결
  backend/src/main/java/org/example/backend/global/config/auth/SecurityConfig.java
  backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
Labels: bug, 😄 BE

#374 [BE][FIX] 논문 엔티티 교수 필드 null 허용
  backend/src/main/java/org/example/backend/thesis/domain/entity/Thesis.java
  backend/src/main/java/org/example/backend/thesis/exception/ThesisExceptionType.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
Labels: 😄 BE

#377 Feature/369 버그 수정
  frontend/public/curriculum-2025.png
  frontend/src/config/videoConfig.ts
  frontend/src/constants/pageContents.ts
  frontend/src/pages/News/News/NewsCreateStyle.ts
  frontend/src/pages/News/News/NewsDetailStyle.ts
  frontend/src/pages/News/News/NewsStyle.ts
Labels: bug

#373 [BE] 개인정보 필터링 & 비밀번호 규칙 수립
  backend/src/main/java/org/example/backend/board/exception/BoardExceptionType.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/common/utils/PersonalInfoFilterUtil.java
  backend/src/main/java/org/example/backend/news/service/NewsService.java
  backend/src/main/java/org/example/backend/users/exception/admin/AdminExceptionType.java
  backend/src/main/java/org/example/backend/users/service/AdminService.java
Labels: enhancement, 😄 BE

#382 #369 style: 뉴스 이미지 렌더링 uri 추가, 이미지 원본 비율 유지되도록
  frontend/src/pages/About/Faculty/ProfessorCreate.tsx
  frontend/src/pages/News/News/News.tsx
  frontend/src/pages/News/News/NewsDetail.tsx
  frontend/src/pages/News/News/NewsDetailStyle.ts
  frontend/src/pages/News/News/NewsStyle.ts
Labels: bug, 🙂 FE

#375 [BE][FEAT] 검색기능에 full text search 적용
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/repository/BoardRepository.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/common/dto/PageRequestDto.java
  backend/src/main/java/org/example/backend/news/controller/NewsController.java
  backend/src/main/java/org/example/backend/news/domain/entity/News.java
  backend/src/main/java/org/example/backend/news/repository/NewsRepository.java
  backend/src/main/java/org/example/backend/seminar/controller/SeminarController.java
  backend/src/main/java/org/example/backend/seminar/repository/SeminarRepository.java
  backend/src/main/java/org/example/backend/seminar/service/SeminarService.java
  backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
  backend/src/main/java/org/example/backend/thesis/domain/entity/Thesis.java
  backend/src/main/java/org/example/backend/thesis/repository/ThesisRepository.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
  backend/src/main/resources/db/schema-ddl.sql
  backend/src/main/resources/db/schema-dml.sql
Labels: enhancement, 😄 BE, refactor

#395 [FE][REACTOR] 전역 Container 구현 및 라우트, 레이아웃 컴포넌트 분리
  frontend/.gitignore
  frontend/public/haru_organization.png
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/AppContent.tsx
  frontend/src/components/layout/AppLayout.tsx
  frontend/src/hooks/queries/index.ts
  frontend/src/hooks/usePageTransition.ts
  frontend/src/hooks/useScrollToTop.ts
  frontend/src/pages/About/About.tsx
  frontend/src/pages/About/AboutStyle.ts
  frontend/src/pages/About/Organization/Organization.tsx
  frontend/src/pages/About/Organization/OrganizationStyle.ts
  frontend/src/pages/About/StudentCouncil/StudentCouncil.tsx
  frontend/src/pages/About/StudentCouncil/StudentCouncilStyle.ts
  frontend/src/pages/Auth/SignInPage.tsx
  frontend/src/pages/Auth/SignInPageStyle.ts
  frontend/src/pages/Graduate/GraduateCurriculum.tsx
  frontend/src/pages/Graduate/GraduateCurriculumStyle.tsx
  frontend/src/pages/Graduate/GraduateOverview.tsx
  frontend/src/pages/Graduate/GraduateOverviewStyle.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/MainStyle.ts
  frontend/src/pages/Main/components/PaperSection/styles.ts
  frontend/src/pages/News/News/News.tsx
  frontend/src/pages/News/News/NewsDetail.tsx
  frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
  frontend/src/pages/News/NoticeBoard/NoticeBoardStyle.ts
  frontend/src/pages/Undergraduate/Curriculum/Curriculum.tsx
  frontend/src/pages/Undergraduate/Curriculum/CurriculumStyle.ts
  frontend/src/pages/Undergraduate/Hyperlink.tsx
  frontend/src/pages/Undergraduate/styles/UndergraduateStyle.tsx
  frontend/src/routes/AppRoutes.tsx
  frontend/src/styles/Container.tsx
  frontend/src/styles/ErrorFallback.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/styles/media.ts
  frontend/src/styles/styled.d.ts
  frontend/src/styles/theme.ts
Labels: 🙂 FE, refactor

#396 #389 fix: 모바일 환경 상단 패딩 로그인 화면만 적용되도록 픽스
  frontend/src/components/layout/AppLayout.tsx
Labels: bug, 🙂 FE

#400 [FIX] CI/CD 빌드 오류
  .github/workflows/main.yml
  frontend/package.json
Labels: bug, 🙂 FE

#401 #389 fix: CI/CD 배포 오류 해결을 위한 빌드 스크립트 수정 2
  .github/workflows/main.yml
  frontend/craco.config.js
  frontend/package.json
Labels: bug, 🙂 FE

#408 cicd/390 내용 병합 및 package.json 롤백
  .github/workflows/backend.yml
  .github/workflows/deploy.yml
  .github/workflows/frontend.yml
  .github/workflows/main.yml
  frontend/package.json
Labels: bug, docker

#411 [FE] [FEAT] 메인페이지 스타일 수정
  frontend/src/components/Banner/MainBanner/MainBanner.tsx
  frontend/src/components/Banner/VideoBanner/VideoSlide.tsx
  frontend/src/components/Header/HeaderStyle.ts
  frontend/src/components/Header/Logo/LogoStyle.ts
  frontend/src/components/Header/Navigation/NavItemStyle.ts
  frontend/src/pages/Main/MainStyle.ts
  frontend/src/styles/Container.tsx
Labels: 🙂 FE

#412 [FE] [FEAT] 메인페이지 스타일 재수정
  frontend/src/components/Header/HeaderStyle.ts
  frontend/src/components/Header/Logo/LogoStyle.ts
  frontend/src/components/Header/Navigation/NavItemStyle.ts
Labels: 🙂 FE

#394 [CI/CD] Flyway를 이용한 DB 형상관리 및 초기 데이터 삽입
  backend/build.gradle
  backend/src/main/java/org/example/backend/blacklist/domain/JwtBlacklist.java
  backend/src/main/java/org/example/backend/department/domain/entity/Department.java
  backend/src/main/java/org/example/backend/professor/domain/entity/Professor.java
  backend/src/main/java/org/example/backend/reservation/domain/Reservation.java
  backend/src/main/resources/db/migration/V20250226__init.sql
  backend/src/main/resources/db/schema-ddl.sql
  backend/src/main/resources/db/schema-dml.sql
Labels: enhancement, 😄 BE

#410 [BE] 예약 서비스 동시성 문제 해결을 위한 비관적 락 적용
  backend/src/main/java/org/example/backend/reservation/repository/ReservationRepository.java
  backend/src/main/java/org/example/backend/reservation/service/ReservationService.java
  backend/src/main/java/org/example/backend/room/repository/RoomRepository.java
Labels: enhancement, 😄 BE

#387 [BE] 로그 파일 저장
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/common/aop/auth/LoginArgumentResolver.java
  backend/src/main/java/org/example/backend/common/aop/logging/Logging.java
  backend/src/main/java/org/example/backend/common/aop/logging/LoggingAspect.java
  backend/src/main/java/org/example/backend/log/domain/RequestResponseLog.java
  backend/src/main/java/org/example/backend/log/repository/LogRepository.java
  backend/src/main/java/org/example/backend/log/service/BulkLogManager.java
  backend/src/main/java/org/example/backend/log/service/LogService.java
Labels: enhancement, 😄 BE, refactor

#415 Refactor/414
  backend/src/main/java/org/example/backend/log/domain/RequestResponseLog.java
  backend/src/main/java/org/example/backend/users/domain/entity/Users.java
  backend/src/main/resources/db/migration/V20250226__init.sql
Labels: bug, refactor

#417 ObjectMapper 생성 시 역직렬화 모듈 등록
  backend/src/main/java/org/example/backend/common/aop/logging/LoggingAspect.java
  backend/src/main/java/org/example/backend/reservation/repository/ReservationRepository.java
Labels: bug

#422 [FE] [FEAT] 헤더 폰트 크기 및 여백 수정
  frontend/src/components/Header/HeaderStyle.ts
  frontend/src/components/Header/Logo/LogoStyle.ts
  frontend/src/components/Header/Navigation/NavItemStyle.ts
  frontend/src/components/Header/TopHeader.tsx
  frontend/src/index.css
Labels: 🙂 FE

#427 [FE] [FEAT] 메인페이지 변경된 컴포넌트 구현
  frontend/package.json
  frontend/src/components/NewsSlider/NewsSlider.tsx
  frontend/src/components/NewsSlider/NewsSliderStyle.ts
  frontend/src/components/layout/AppLayout.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/MainStyle.ts
  frontend/src/pages/Main/components/ButtonListSection/ButtonListSection.tsx
  frontend/src/pages/Main/components/ButtonListSection/ButtonListSectionStyle.ts
  frontend/src/pages/Main/components/ButtonListSection/data.ts
  frontend/src/pages/Main/components/VerticalButtonSection/VerticalButtonSection.tsx
  frontend/src/pages/Main/components/VerticalButtonSection/VerticalButtonSectionStyle.ts
  frontend/src/pages/Main/components/VerticalButtonSection/data.ts
  frontend/src/styles/theme.ts
Labels: 🙂 FE
