Repository urinaner/sejong-dibb, pull requests merged in 2025-03, with the labels that each got.

#424 [BE] getwriter() has already been called for this response 해결 & 뉴스 조회수 로직 추가
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/news/controller/NewsController.java
  backend/src/main/java/org/example/backend/news/repository/NewsRepository.java
  backend/src/main/java/org/example/backend/news/service/NewsService.java
Labels: bug, enhancement, 😄 BE, refactor

#428 [FE][REFACTOR] 교수 학력 정보 기능 추가 및 컴포넌트 리팩토링
  backend/src/main/java/org/example/backend/professor/domain/dto/ProfessorResDto.java
  backend/src/main/java/org/example/backend/professor/repository/ProfessorRepository.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
  backend/src/main/java/org/example/backend/thesis/domain/entity/Thesis.java
  backend/src/main/java/org/example/backend/thesis/repository/ThesisRepository.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
  backend/src/test/java/org/example/backend/professor/repository/ProfessorRepositoryTest.java
  backend/src/test/java/org/example/backend/professor/service/ProfessorServiceTest.java
  frontend/package.json
  frontend/src/config/apiConfig.ts
  frontend/src/hooks/queries/useProfessor.ts
  frontend/src/pages/About/Faculty/FacultyStyle.ts
  frontend/src/pages/About/Faculty/Professor.tsx
  frontend/src/pages/About/Faculty/Professor/index.tsx
  frontend/src/pages/About/Faculty/ProfessorCard.tsx
  frontend/src/pages/About/Faculty/ProfessorCreate.tsx
  frontend/src/pages/About/Faculty/ProfessorCreate/index.tsx
  frontend/src/pages/About/Faculty/ProfessorDetail.tsx
  frontend/src/pages/About/Faculty/ProfessorDetail/index.tsx
  frontend/src/pages/About/Faculty/ProfessorDetailStyle.ts
  frontend/src/pages/About/Faculty/ProfessorEdit.tsx
  frontend/src/pages/About/Faculty/ProfessorEdit/index.tsx
  frontend/src/pages/About/Faculty/ProfessorEditStyle.ts
  frontend/src/pages/About/Faculty/ProfileSection.tsx
  frontend/src/pages/About/Faculty/ProfileSectionStyle.ts
  frontend/src/pages/About/Faculty/TabSection.tsx
  frontend/src/pages/About/Faculty/TabSectionStyle.ts
  frontend/src/pages/About/Faculty/components/ProfileSection.tsx
  frontend/src/pages/About/Faculty/components/Tabs/BasicInfo.tsx
  frontend/src/pages/About/Faculty/components/Tabs/Publications.tsx
  frontend/src/pages/About/Faculty/components/Tabs/TabSection.tsx
  frontend/src/pages/About/Faculty/components/common/Button/Button.tsx
  frontend/src/pages/About/Faculty/components/common/PageContainer/PageContainer.tsx
  frontend/src/pages/About/Faculty/components/common/ProfessorCard.tsx
  frontend/src/pages/About/Faculty/components/common/ProfessorFormStyles.ts
  frontend/src/pages/About/Faculty/components/common/ProfessorFrom.tsx
  frontend/src/pages/About/Faculty/tabs/BasicInfo.tsx
  frontend/src/pages/About/Faculty/tabs/Publications.tsx
  frontend/src/pages/About/Faculty/tabs/PublicationsStyle.ts
  frontend/src/pages/About/Faculty/types.ts
  frontend/src/types/api/professor.ts
  frontend/src/types/professor.ts
Labels: 🙂 FE, refactor

#430 [FE][BUG] 수정사항 기존 정보 반영 안됨
  frontend/src/pages/About/Faculty/components/common/ProfessorFormStyles.ts
  frontend/src/pages/About/Faculty/components/common/ProfessorFrom.tsx
Labels: bug, 🙂 FE

#431 Feature/426
  frontend/src/components/NewsSlider/NewsCard.tsx
  frontend/src/components/NewsSlider/NewsSlider.tsx
  frontend/src/pages/Main/components/ButtonListSection/ButtonListSection.tsx
  frontend/src/pages/Main/components/ButtonListSection/ButtonListSectionStyle.ts
  frontend/src/pages/Main/components/ButtonListSection/data.ts
  frontend/src/pages/Main/components/VerticalButtonSection/VerticalButtonSectionStyle.ts
  frontend/src/pages/Main/components/VerticalButtonSection/data.ts
Labels: 🙂 FE

#432 [FE] [FEAT] 메인페이지 세미나 버튼 페이지 이동 구현
  frontend/src/pages/Main/components/ButtonListSection/ButtonListSection.tsx
  frontend/src/pages/Main/components/ButtonListSection/ButtonListSectionStyle.ts
  frontend/src/pages/Main/components/ButtonListSection/data.ts
  frontend/src/pages/Main/components/VerticalButtonSection/data.ts
Labels: 🙂 FE

#433 [FE] [FEAT] 뉴스 이미지 오류 수정
  frontend/src/pages/News/News/News.tsx
  frontend/src/pages/News/News/NewsStyle.ts
Labels: 🙂 FE

#434 [Fix/429][FE] 메인페이지 반응형, 교수 수정
  frontend/src/pages/About/Faculty/Professor/index.tsx
  frontend/src/pages/About/Faculty/components/common/ProfessorCard.tsx
Labels: bug, 🙂 FE

#436 [FE][Feature/435] 검색기능 CRUD 구현
  frontend/src/common/SearchComponent.tsx
  frontend/src/common/SearchableBoard.tsx
  frontend/src/config/apiConfig.ts
  frontend/src/constants/pageContents.ts
  frontend/src/features/calendarReservation/components/Calendar/components/RoomInfo/index.tsx
  frontend/src/hooks/queries/useNews.ts
  frontend/src/hooks/queries/useNotice.ts
  frontend/src/hooks/queries/useSeminar.ts
  frontend/src/hooks/queries/useThesis.ts
  frontend/src/pages/News/News/News.tsx
  frontend/src/pages/News/News/NewsCreate.tsx
  frontend/src/pages/News/News/NewsDetail.tsx
  frontend/src/pages/News/News/NewsStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
  frontend/src/pages/News/Thesis/ThesisList.tsx
  frontend/src/pages/News/Thesis/ThesisSearchBoard.tsx
  frontend/src/pages/News/Thesis/ThesisStyle.ts
  frontend/src/pages/Seminar/SeminarList.tsx
  frontend/src/types/api/notice.ts
Labels: enhancement, 🙂 FE

#437 #435 style: 공지 사항 세부 컨테이너 픽스
  frontend/src/pages/News/NoticeBoard/NoticeDetail.tsx
Labels: bug, 🙂 FE

#439 논문 및 세미나가 BaseEntity를 상속
  backend/src/main/java/org/example/backend/seminar/domain/entity/Seminar.java
  backend/src/main/java/org/example/backend/thesis/domain/entity/Thesis.java
  backend/src/main/resources/db/migration/V20250306_01__add_created_updated_columns.sql
  backend/src/main/resources/db/schema-dml.sql
Labels: 😄 BE

#441 [FE] [FEAT] 일부 텍스트 및 디자인 수정
  frontend/src/components/Footer/Footer.tsx
  frontend/src/pages/Main/components/ButtonListSection/ButtonListSection.tsx
  frontend/src/pages/Main/components/ButtonListSection/ButtonListSectionStyle.ts
  frontend/src/pages/Seminar/SeminarCreate.tsx
  frontend/src/pages/Seminar/SeminarDetail.tsx
  frontend/src/pages/Seminar/SeminarEdit.tsx
  frontend/src/pages/Seminar/SeminarList.tsx
Labels: 🙂 FE

#444 #435 fix: 뉴스 생성시 명세 누락 해결
  frontend/src/AppContent.tsx
  frontend/src/config/apiConfig.ts
  frontend/src/hooks/queries/useNews.ts
  frontend/src/pages/News/News/NewsCreate.tsx
Labels: bug, 🙂 FE

#446 [FE] [FEAT] 전체적인 디자인 깨짐 수정
  frontend/src/AppContent.tsx
  frontend/src/components/Banner/MainBanner/MainBanner.tsx
  frontend/src/components/Footer/FooterStyle.ts
  frontend/src/components/Header/HeaderStyle.ts
  frontend/src/components/NewsSlider/NewsSlider.tsx
  frontend/src/components/NewsSlider/NewsSliderStyle.ts
  frontend/src/config/apiConfig.ts
  frontend/src/hooks/queries/useNotice.ts
  frontend/src/pages/Graduate/GraduateOverviewStyle.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/MainStyle.ts
  frontend/src/pages/Main/components/AnnouncementSection/AnnouncementList.tsx
  frontend/src/pages/Main/components/AnnouncementSection/index.tsx
  frontend/src/pages/Main/components/ButtonListSection/ButtonListSection.tsx
  frontend/src/pages/Main/components/ButtonListSection/ButtonListSectionStyle.ts
  frontend/src/pages/Main/components/VerticalButtonSection/VerticalButtonSectionStyle.ts
  frontend/src/pages/News/News/NewsStyle.ts
  frontend/src/styles/Container.tsx
  frontend/src/styles/theme.ts
Labels: 🙂 FE

#447 [FE] [FIX] 공지사항 오류 수정
  frontend/src/hooks/queries/useNotice.ts
  frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
Labels: 🙂 FE

#442 [BE] 로컬 캐시 도입
  backend/build.gradle
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/global/config/cache/CacheConfig.java
  backend/src/main/java/org/example/backend/global/config/cache/CacheType.java
  backend/src/main/java/org/example/backend/news/service/NewsService.java
  backend/src/main/java/org/example/backend/seminar/service/SeminarService.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
Labels: enhancement, 😄 BE

#445 #435 fix: 교수 수정시 이전 사항 누락 픽스
  frontend/src/pages/About/Faculty/ProfessorEdit/index.tsx
  frontend/src/pages/About/Faculty/components/common/ProfessorFrom.tsx
  frontend/src/pages/About/Faculty/types.ts
  frontend/src/pages/Auth/SignInPageStyle.ts
  frontend/src/types/api/professor.ts
Labels: bug, 🙂 FE

#450 공지사항, 세미나 넘버링
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/domain/dto/BoardResDto.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/seminar/domain/dto/SeminarResDto.java
  backend/src/main/java/org/example/backend/seminar/service/SeminarService.java
  backend/src/main/resources/db/schema-dml.sql
Labels: 😄 BE
