Repository urinaner/sejong-dibb, pull requests merged in 2025-01, with the labels that each got.

#240 [BE] [FEAT] 뉴스 CRUD API 생성
  backend/backup.sql
  backend/src/main/java/org/example/backend/news/controller/NewsController.java
  backend/src/main/java/org/example/backend/news/domain/dto/NewsReqDto.java
  backend/src/main/java/org/example/backend/news/domain/dto/NewsResDto.java
  backend/src/main/java/org/example/backend/news/domain/entity/News.java
  backend/src/main/java/org/example/backend/news/exception/NewsException.java
  backend/src/main/java/org/example/backend/news/exception/NewsExceptionType.java
  backend/src/main/java/org/example/backend/news/repository/NewsRepository.java
  backend/src/main/java/org/example/backend/news/service/NewsService.java
  backend/src/main/resources/data.sql
Labels: enhancement, 😄 BE

#242 [FE] 대학원 커리큘럼 페이지 구현
  frontend/public/graduate-curriculum1.png
  frontend/public/graduate-curriculum2.png
  frontend/src/AppContent.tsx
  frontend/src/pages/Graduate/GraduateCurriculum.tsx
  frontend/src/pages/Graduate/GraduateCurriculumStyle.tsx
Labels: enhancement, 🙂 FE

#236 [FE] [FEAT] 세미나 CRUD 페이지 구현
  frontend/src/AppContent.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/HeaderStyle.ts
  frontend/src/components/Header/Logo/Logo.tsx
  frontend/src/components/Header/Logo/LogoStyle.ts
  frontend/src/components/Header/MobileMenu/MobileMenu.tsx
  frontend/src/components/Header/MobileMenu/MobileMenuStyle.ts
  frontend/src/components/Header/Navigation/Navigation.tsx
  frontend/src/components/Header/constants.ts
  frontend/src/config/apiConfig.ts
  frontend/src/constants/pageContents.ts
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/MainStyle.ts
  frontend/src/pages/Seminar/SeminarCreate.tsx
  frontend/src/pages/Seminar/SeminarDetail.tsx
  frontend/src/pages/Seminar/SeminarEdit.tsx
  frontend/src/pages/Seminar/SeminarList.tsx
Labels: enhancement, 🙂 FE

#239 feat : 조회수 로직 추가
  backend/src/main/java/org/example/backend/board/controller/BoardController.java
  backend/src/main/java/org/example/backend/board/repository/BoardRepository.java
  backend/src/main/java/org/example/backend/board/service/BoardService.java
Labels: enhancement, 😄 BE

#249 [FE] 교수소개, 논문, 게시글 디자인 수정
  frontend/package.json
  frontend/src/AppContent.tsx
  frontend/src/pages/About/Faculty/TabSectionStyle.ts
  frontend/src/pages/About/Faculty/tabs/Publications.tsx
  frontend/src/pages/About/Faculty/tabs/PublicationsStyle.ts
  frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
  frontend/src/pages/News/NoticeBoard/NoticeBoardStyle.ts
  frontend/src/pages/News/NoticeBoard/hooks/useNoticeBoard.ts
  frontend/src/pages/News/Thesis/ThesisList.tsx
  frontend/src/pages/News/Thesis/ThesisStyle.ts
  frontend/src/pages/Seminar/SeminarList.tsx
Labels: 🙂 FE, refactor

#255 [BE] fix: 예약 로직 변경
  backend/build.gradle
  backend/src/main/java/org/example/backend/admin/service/AdminService.java
  backend/src/main/java/org/example/backend/global/aop/AuthAdmin.java
  backend/src/main/java/org/example/backend/global/aop/AuthAdminResolver.java
  backend/src/main/java/org/example/backend/global/aop/AuthUser.java
  backend/src/main/java/org/example/backend/global/aop/AuthUserResolver.java
  backend/src/main/java/org/example/backend/global/config/sj/SjConfig.java
  backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
  backend/src/main/java/org/example/backend/reservation/controller/ReservationController.java
  backend/src/main/java/org/example/backend/reservation/domain/Reservation.java
  backend/src/main/java/org/example/backend/reservation/domain/dto/ReservationCreateDto.java
  backend/src/main/java/org/example/backend/reservation/domain/dto/ReservationDeleteRequest.java
  backend/src/main/java/org/example/backend/reservation/domain/dto/ReservationResDto.java
  backend/src/main/java/org/example/backend/reservation/exception/ReservationExceptionType.java
  backend/src/main/java/org/example/backend/reservation/service/ReservationService.java
  backend/src/main/java/org/example/backend/user/controller/UserController.java
  backend/src/main/java/org/example/backend/user/domain/dto/UserReqDto.java
  backend/src/main/java/org/example/backend/user/domain/dto/UserResDto.java
  backend/src/main/java/org/example/backend/user/domain/entity/User.java
  backend/src/main/java/org/example/backend/user/exception/UserException.java
  backend/src/main/java/org/example/backend/user/exception/UserExceptionType.java
  backend/src/main/java/org/example/backend/user/repository/UserRepository.java
  backend/src/main/java/org/example/backend/user/service/UserService.java
Labels: 😄 BE, refactor

#254 [BE] [FIX] 세미나 시간 추가 및 삭제기능 수정
  backend/src/main/java/org/example/backend/seminar/domain/dto/SeminarReqDto.java
  backend/src/main/java/org/example/backend/seminar/domain/dto/SeminarResDto.java
  backend/src/main/java/org/example/backend/seminar/domain/entity/Seminar.java
  backend/src/main/java/org/example/backend/seminar/service/SeminarService.java
  backend/src/main/resources/data.sql
Labels: bug, 😄 BE

#266 [BE] [REFACTOR] accessToken 유효시간 증가
  backend/src/main/java/org/example/backend/jwt/LoginFilter.java
Labels: 😄 BE, refactor

#270 [BE] [FIX] CRUD 기능 점검
  backend/src/main/java/org/example/backend/news/controller/NewsController.java
  backend/src/main/java/org/example/backend/news/domain/dto/NewsReqDto.java
  backend/src/main/java/org/example/backend/news/service/NewsService.java
  backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
  backend/src/main/java/org/example/backend/professor/domain/dto/ProfessorReqDto.java
  backend/src/main/java/org/example/backend/professor/domain/dto/ProfessorResDto.java
  backend/src/main/java/org/example/backend/professor/domain/entity/Professor.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
  backend/src/test/java/org/example/backend/professor/controller/ProfessorControllerTest.java
  backend/src/test/java/org/example/backend/professor/repository/ProfessorRepositoryTest.java
  backend/src/test/java/org/example/backend/professor/service/ProfessorServiceTest.java
Labels: bug, 😄 BE

#271 [FE] 메인 페이지 최신 세미나 정보 표시
  frontend/src/AppContent.tsx
  frontend/src/components/NewsSlider/NewsSliderStyle.ts
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/MainStyle.ts
Labels: enhancement, 🙂 FE

#272 [BE][FIX] accessToken 만료 시간 수정
  backend/src/main/java/org/example/backend/jwt/JWTUtil.java
  backend/src/main/java/org/example/backend/jwt/LoginFilter.java
Labels: bug, 😄 BE

#274 [BE] fix: application/octet-stream 변환로직 추가
  backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
  backend/src/main/java/org/example/backend/global/util/OctetStreamReadMsgConverter.java
Labels: bug, 😄 BE

#278 [FE] 전체 페이지 폰트 변경
  frontend/package.json
  frontend/public/index.html
  frontend/src/common/Button/Button.tsx
  frontend/src/components/Banner/MainBanner/MainBanner.tsx
  frontend/src/components/Banner/PageBanner/PageBanner.tsx
  frontend/src/components/Banner/VideoBanner/VideoSlide.tsx
  frontend/src/components/Footer/FooterStyle.ts
  frontend/src/components/Header/Logo/LogoStyle.ts
  frontend/src/components/Modal/components/ModalHeader.tsx
  frontend/src/components/Modal/context/ModalContext.tsx
  frontend/src/index.css
  frontend/src/pages/About/AboutStyle.ts
  frontend/src/pages/About/Faculty/FacultyStyle.ts
  frontend/src/pages/About/Faculty/ProfessorDetailStyle.ts
  frontend/src/pages/About/Faculty/ProfessorEditStyle.ts
  frontend/src/pages/About/Faculty/ProfileSectionStyle.ts
  frontend/src/pages/About/Faculty/TabSectionStyle.ts
  frontend/src/pages/About/Faculty/tabs/PublicationsStyle.ts
  frontend/src/pages/Auth/SignInPageStyle.ts
  frontend/src/pages/Graduate/GraduateOverviewStyle.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/MainStyle.ts
  frontend/src/pages/News/News/NewsCreateStyle.ts
  frontend/src/pages/News/News/NewsDetailStyle.ts
  frontend/src/pages/News/Thesis/ThesisDetailStyle.ts
  frontend/src/pages/Seminar/SeminarDetail.tsx
  frontend/src/styles/GlobalStyle.ts
Labels: enhancement, 🙂 FE

#281 [FIX] [FE] framer 타입오류, 쿠키 설정
  frontend/package.json
  frontend/src/api/index.ts
  frontend/src/api/news/api.ts
  frontend/src/api/news/index.ts
  frontend/src/api/news/types.ts
  frontend/src/components/NewsSlider/NewsCard.tsx
  frontend/src/hooks/queries/useNews.ts
  frontend/src/index.tsx
  frontend/src/pages/About/Faculty/ProfessorCreate.tsx
  frontend/src/pages/News/News/News.tsx
  frontend/src/pages/News/News/NewsCreate.tsx
Labels: bug, 🙂 FE

#286 [FE] [REFACTOR] 메인 페이지 React Query 도입 및 컴포넌트 분리
  frontend/src/components/LoadingSpinner/LoadingSpinner.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/Main/components/AnnouncementSection/AnnouncementList.tsx
  frontend/src/pages/Main/components/AnnouncementSection/AnnouncementTab.tsx
  frontend/src/pages/Main/components/AnnouncementSection/index.tsx
  frontend/src/pages/Main/components/NewsSection/index.tsx
  frontend/src/pages/Main/components/NewsSection/types.ts
  frontend/src/pages/Main/components/PaperSection/PaperCard.tsx
  frontend/src/pages/Main/components/PaperSection/index.tsx
  frontend/src/pages/Main/components/PaperSection/styles.ts
  frontend/src/pages/Main/components/PaperSection/types.ts
  frontend/src/pages/Main/components/SeminarSection/CurrentSeminar.tsx
  frontend/src/pages/Main/components/SeminarSection/SeminarReservation.tsx
  frontend/src/pages/Main/components/SeminarSection/index.tsx
  frontend/src/pages/Main/components/SeminarSection/types.ts
  frontend/src/pages/Main/components/ShortcutSection/ShortcutItem.tsx
  frontend/src/pages/Main/components/ShortcutSection/index.tsx
  frontend/src/pages/Main/components/ShortcutSection/types.ts
  frontend/src/pages/Main/constants/index.ts
  frontend/src/pages/Main/hooks/useMainPageData.ts
Labels: enhancement, 🙂 FE, refactor

#283 [BE] 세종대 구성원(교수, 교직원, 학생) 통합 로그인 로직 구현
  backend/build.gradle
  backend/src/main/java/org/example/backend/users/dto/SjLoginReq.java
  backend/src/main/java/org/example/backend/users/dto/SjUserProfile.java
  backend/src/main/java/org/example/backend/users/service/SjAuthService.java
  backend/src/test/java/org/example/backend/ControllerTestSupport.java
  backend/src/test/java/org/example/backend/SjTest.java
  backend/src/test/java/org/example/backend/professor/service/ProfessorServiceTest.java
Labels: enhancement, 😄 BE

#292 [BE] s3 → 로컬 저장 로직 작성
  backend/src/main/java/org/example/backend/board/service/BoardService.java
  backend/src/main/java/org/example/backend/global/config/auth/SecurityConfig.java
  backend/src/main/java/org/example/backend/global/config/aws/LocalFileUploader.java
  backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
  backend/src/main/java/org/example/backend/news/service/NewsService.java
  backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
  backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
Labels: enhancement, 😄 BE

#296 [FE] 세미나페이지 반응형 디자인 구현
  frontend/src/pages/About/Organization/OrganizationStyle.ts
  frontend/src/pages/Seminar/SeminarDetail.tsx
  frontend/src/pages/Seminar/SeminarList.tsx
Labels: enhancement, 🙂 FE

#298 [FE] 연구논문 조회 페이지 모바일 반응형 디자인 구현
  frontend/src/pages/News/Thesis/ThesisDetailStyle.ts
  frontend/src/pages/News/Thesis/ThesisList.tsx
  frontend/src/pages/News/Thesis/ThesisStyle.ts
  frontend/src/pages/Seminar/SeminarDetail.tsx
  frontend/src/pages/Seminar/SeminarList.tsx
Labels: enhancement, 🙂 FE

#300 [FE] [BUG] 폰트 설정 복구
  frontend/public/index.html
  frontend/src/components/Banner/MainBanner/MainBanner.tsx
  frontend/src/components/Banner/PageBanner/PageBanner.tsx
  frontend/src/components/Banner/VideoBanner/VideoSlide.tsx
  frontend/src/components/Footer/FooterStyle.ts
  frontend/src/components/Header/Logo/LogoStyle.ts
  frontend/src/components/Modal/components/ModalHeader.tsx
  frontend/src/components/Modal/context/ModalContext.tsx
  frontend/src/pages/About/AboutStyle.ts
  frontend/src/pages/About/Faculty/FacultyStyle.ts
  frontend/src/pages/About/Faculty/ProfessorDetailStyle.ts
  frontend/src/pages/About/Faculty/ProfessorEditStyle.ts
  frontend/src/pages/About/Faculty/ProfileSectionStyle.ts
  frontend/src/pages/About/Faculty/TabSectionStyle.ts
  frontend/src/pages/About/Faculty/tabs/PublicationsStyle.ts
  frontend/src/pages/Auth/SignInPageStyle.ts
  frontend/src/pages/Graduate/GraduateOverviewStyle.tsx
  frontend/src/pages/Main/MainStyle.ts
  frontend/src/pages/News/News/NewsCreateStyle.ts
  frontend/src/pages/News/News/NewsDetailStyle.ts
  frontend/src/pages/News/Thesis/ThesisDetailStyle.ts
  frontend/src/styles/GlobalStyle.ts
Labels: bug, 🙂 FE

#306 refactor: 예약 적용
  backend/src/main/java/org/example/backend/reservation/controller/ReservationController.java
  backend/src/main/java/org/example/backend/reservation/domain/Reservation.java
  backend/src/main/java/org/example/backend/reservation/domain/dto/ReservationCreateDto.java
  backend/src/main/java/org/example/backend/reservation/domain/dto/ReservationResDto.java
  backend/src/main/java/org/example/backend/reservation/service/ReservationService.java
  backend/src/main/resources/data.sql
Labels: 😄 BE

#310 [BE][FIX] 예약 엔티티 없는 필드 임베딩 삭제
  backend/src/main/resources/data.sql
Labels: bug

#308 [FE][REAFACTOR] 연구논문, 교수 상세 논문 반응형 로직
  frontend/public/seminarRoom1.jpeg
  frontend/public/seminarRoom1.jpg
  frontend/src/components/Footer/FooterStyle.ts
  frontend/src/pages/About/Faculty/ProfileSection.tsx
  frontend/src/pages/About/Faculty/ProfileSectionStyle.ts
  frontend/src/pages/About/Faculty/TabSectionStyle.ts
  frontend/src/pages/About/Faculty/tabs/Publications.tsx
  frontend/src/pages/About/Faculty/tabs/PublicationsStyle.ts
  frontend/src/pages/Main/components/NewsSection/index.tsx
  frontend/src/pages/News/Thesis/ThesisList.tsx
  frontend/src/pages/News/Thesis/ThesisStyle.ts
  frontend/src/pages/SeminarRoom/Reservation.tsx
Labels: enhancement, 🙂 FE

#312 [FE][REFACTOR] 상대경로 uri 지정, 개발환경 및 프로덕션 환경 분리
  frontend/.env.production
  frontend/src/config/apiConfig.ts
Labels: setting, 🙂 FE

#314 [FE] [REFACTOR] 메인 동영상 배너 CDN 및 성능최적화
  frontend/.env.development
  frontend/.env.production
  frontend/src/AppContent.tsx
  frontend/src/components/Banner/MainBanner/MainBanner.tsx
  frontend/src/components/Banner/VideoBanner/index.tsx
  frontend/src/components/Banner/VideoBanner/types.ts
  frontend/src/config/videoConfig.ts
  frontend/src/hooks/useVideosQuality.ts
  frontend/src/utils/videos.ts
Labels: enhancement, setting, 🙂 FE, refactor
